### ISSUE TITLE
NanoPlot Error-GridION

### ISSUE THREAD

**Issue by tmmurtha** [wdecoster/NanoPlot#101]
I tried to run my concatenated files with nanoplot and keep getting this message.  I must admit, I'm very new to this, so I may have made an error.  Any guidance would be appreciated!

I concatenated my gridion data with cat sequencing_summary* > concat/concat_summary.txt
and then I ran: NanoPlot --summary concat_summary.txt -o nanoplot

here's the error messag:

grid@GXB01209:/data/basecalled/17-10375_Reading/GA50000/concat$ NanoPlot --summary concat_summary.txt -o nanoplot
/home/grid/miniconda3/lib/python3.5/concurrent/futures/process.py:175: DtypeWarning: Columns (3,4,5,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  r = call_item.fn(*call_item.args, **call_item.kwargs)

If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/home/grid/miniconda3/lib/python3.5/site-packages/pandas/core/nanops.py", line 128, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/pandas/core/nanops.py", line 507, in reduction
    result = getattr(values, meth)(axis)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
TypeError: unorderable types: str() <= float()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grid/miniconda3/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/home/grid/miniconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 63, in main
    barcoded=args.barcoded)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/nanoget/nanoget.py", line 79, in get_input
    datadf = calculate_start_time(datadf)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/nanoget/nanoget.py", line 129, in calculate_start_time
    df["start_time"] = df["time_arr"] - df["time_arr"].min()
  File "/home/grid/miniconda3/lib/python3.5/site-packages/pandas/core/generic.py", line 9613, in stat_func
    numeric_only=numeric_only)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/pandas/core/series.py", line 3221, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/pandas/core/nanops.py", line 131, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/pandas/core/nanops.py", line 507, in reduction
    result = getattr(values, meth)(axis)
  File "/home/grid/miniconda3/lib/python3.5/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
TypeError: unorderable types: str() <= float()

**Comment by wdecoster** [comment]
This is expected, as by concatenating you are repeating the headerline of the summary files.

The simpliest way to prevent this is to just use NanoPlot with all separate summaries:

`NanoPlot --summary sequencing_summary* -o nanoplot`

This has the additional advantage that data is extracted in parallel if you have a multicore machine.

If you insist in concatenating the summaries, for example for NanoComp, the solution would be to use 
`awk 'FNR>1 || NR==1' sequencing_summary* > concat_summary.txt`

Note that you can also gzip the summaries.

**Comment by tmmurtha** [comment]
Thank you!
