### ISSUE TITLE
Documentation for multiple colors

### ISSUE THREAD

**Issue by dfornika** [wdecoster/NanoPlot#102]
There doesn't seem to be an example in the documentation showing how to pass multiple colors. I'm running NanoPlot on 13 fastq input files (barcode01..barcode12 + unclassified). 

If the colors are passed in with the wrong format, the user gets the following error:

```
2018-10-19 16:08:40,933 Nanoplotter: Invalid color '#8dd3c7','#ffffb3','#bebada','#fb8072','#80b1d3','#fdb462','#b3de69','#fccde5','#d9d9d9','#bc80bd','#ccebc5','#ffed6f', '#0ef26d', using default.
2018-10-19 16:08:40,933 Nanoplotter: Creating length plots for Read length.
2018-10-19 16:08:41,351 Nanoplotter: Using 6310888 reads maximum of 33084bp.
2018-10-19 16:09:29,796 color kwarg must have one color per dataset
Traceback (most recent call last):
  File "/opt/miniconda2/envs/nanoplot-1.18.2/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 92, in main
    plots = make_plots(datadf, settings)
  File "/opt/miniconda2/envs/nanoplot-1.18.2/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 313, in make_plots
    title=settings["title"])
  File "/opt/miniconda2/envs/nanoplot-1.18.2/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 234, in length_plots
    alpha=0.8))
  File "/opt/miniconda2/envs/nanoplot-1.18.2/lib/python3.6/site-packages/seaborn/distributions.py", line 225, in distplot
    color=hist_color, **hist_kws)
  File "/opt/miniconda2/envs/nanoplot-1.18.2/lib/python3.6/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/opt/miniconda2/envs/nanoplot-1.18.2/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6613, in hist
    raise ValueError("color kwarg must have one color per dataset")
ValueError: color kwarg must have one color per dataset
```

...I wonder if it would be possible to define a default palette of up to 13 colors? Is it a bad idea to run all 13 samples through NanoPlot at once? Maybe this is related to #84?

**Comment by dfornika** [comment]
Thanks, doing that right now.
