### ISSUE TITLE
TypeError: unorderable types: str() <= float()

### ISSUE THREAD

**Issue by vnimmunol** [wdecoster/NanoPlot#105]
While trying to run NanoPlot I receive the following error. I don't know if the problem is with my summary file or its a software issue. Can you please help me to check? I have already tried updating NanoPlot to current version by pip install nanoplot -U.

2018-11-05 18:28:15,928 NanoPlot 1.19.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, font_scale=1, format='png', listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='.', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=['130718_P_cynomolgi.sequencing_summary.txt'], threads=4, title=None, verbose=False)
2018-11-05 18:28:15,929 Python version is: 3.5.4 (default, Dec 15 2017, 10:34:53)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
2018-11-05 18:28:15,929 Nanoplotter: valid output format png
2018-11-05 18:28:15,936 Nanoget: Collecting metrics from summary file 130718_P_cynomolgi.sequencing_summary.txt for 1D sequencing
2018-11-05 18:28:18,249 Nanoget: Finished collecting statistics from summary file 130718_P_cynomolgi.sequencing_summary.txt
2018-11-05 18:28:19,086 Reduced DataFrame memory usage from 293.1962127685547Mb to 238.62672901153564Mb
2018-11-05 18:28:20,692 unorderable types: str() <= float()
Traceback (most recent call last):
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/pandas/core/nanops.py", line 128, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/pandas/core/nanops.py", line 507, in reduction
    result = getattr(values, meth)(axis)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
TypeError: unorderable types: str() <= float()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 63, in main
    barcoded=args.barcoded)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/nanoget/nanoget.py", line 79, in get_input
    datadf = calculate_start_time(datadf)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/nanoget/nanoget.py", line 129, in calculate_start_time
    df["start_time"] = df["time_arr"] - df["time_arr"].min()
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/pandas/core/generic.py", line 9613, in stat_func
    numeric_only=numeric_only)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/pandas/core/series.py", line 3221, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/pandas/core/nanops.py", line 131, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/pandas/core/nanops.py", line 507, in reduction
    result = getattr(values, meth)(axis)
  File "/tools/ActivePython-3.5/lib/python3.5/site-packages/numpy-1.13.1-py3.5-linux-x86_64.egg/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
TypeError: unorderable types: str() <= float()

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this.
Would it be possible to share the summary file which caused this error?

Cheers,
Wouter

**Comment by vnimmunol** [comment]
Hi Wouter, I have posted the summary file to the link below. Thanks for looking through it!

https://1drv.ms/f/s!AvJejmnV8kASqzGeOEZLZvPpm6Ig

**Comment by wdecoster** [comment]
Hi,

I took a quick look at the file and noticed the header line is repeated multiple times. Presumably, you combined multiple files using `cat`?

Two options to solve that:
Use a different command for combining the summaries
`awk 'FNR>1 || NR==1' sequencing_summaries* > combined_summary.tsv`

Or don't combine the summaries (which is also faster because information extraction can be done in parallel)
`NanoPlot --summary sequencing_summaries*`

Cheers,
Wouter

**Comment by wdecoster** [comment]
That should be easy to fix, see https://github.com/wdecoster/NanoPlot/issues/88

**Comment by vnimmunol** [comment]
Great! I did "pip install seaborn -U" and now it all works! Thanks for your quick replies.
