### ISSUE TITLE
options don't work?

### ISSUE THREAD

**Issue by rehgar12** [wdecoster/NanoPlot#106]
Maybe my install is improper, but I can't even get the --help option to work:
```
NanoPlot -h
Traceback (most recent call last):
  File "/home/rp/miniconda2/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/home/rp/miniconda2/lib/python2.7/site-packages/nanoplot/NanoPlot.py", line 35, in main
    args = get_args()
  File "/home/rp/miniconda2/lib/python2.7/site-packages/nanoplot/NanoPlot.py", line 234, in get_args
    args = parser.parse_args()
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 996, in __call__
    parser.print_help()
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 2307, in format_help
    formatter.add_arguments(action_group._group_actions)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 275, in add_arguments
    self.add_argument(action)
  File "/home/rp/miniconda2/lib/python2.7/argparse.py", line 260, in add_argument
    invocations = [get_invocation(action)]
  File "/home/rp/miniconda2/lib/python2.7/site-packages/nanoplot/utils.py", line 14, in _format_action_invocation
    return super()._format_action_invocation(action)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by wdecoster** [comment]
Probably same reason as https://github.com/wdecoster/NanoPlot/issues/107

> you are using python2.7, which is not supported. NanoPlot is written for Python3. Please let me know if issues persist after fixing this part.
