### ISSUE TITLE
something with bins?

### ISSUE THREAD

**Issue by rehgar12** [wdecoster/NanoPlot#107]
Something with bins, looks like it's still not fixed (re: issue #77). Though I'm also not able to confirm version (I just installed it 11/13/2018) as the -v option also produces a Traceback.

```
If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!



Traceback (most recent call last):
  File "/home/rp/miniconda2/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/home/rp/miniconda2/lib/python2.7/site-packages/nanoplot/NanoPlot.py", line 85, in main
    plots = make_plots(datadf, settings)
  File "/home/rp/miniconda2/lib/python2.7/site-packages/nanoplot/NanoPlot.py", line 327, in make_plots
    title=settings["title"])
  File "/home/rp/miniconda2/lib/python2.7/site-packages/nanoplotter/nanoplotter.py", line 373, in length_plots
    color=color)
  File "/home/rp/miniconda2/lib/python2.7/site-packages/seaborn/distributions.py", line 225, in distplot
    color=hist_color, **hist_kws)
  File "/home/rp/miniconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/home/rp/miniconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 6530, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/home/rp/miniconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 719, in histogram
    '`bins` must be an integer, a string, or an array')
TypeError: `bins` must be an integer, a string, or an array
```

**Comment by wdecoster** [comment]
At least one of the issues is that you are using python2.7, which is not supported. NanoPlot is written for Python3. Please let me know if issues persist after fixing this part.

**Comment by rehgar12** [comment]
yep that was it... for others with this problem:
```
1. setup virtual python3 env
python3 -m venv env
source ./env/bin/activate 
1. install
pip install nanopack
2. check for updates
pip install nanopack --upgrade
```
