### ISSUE TITLE
Nanoplot Syntax Error

### ISSUE THREAD

**Issue by garbog2** [wdecoster/NanoPlot#117]
Hi there,
After updating Nanoplot, I tried running 
`Nanoplot -h` and got the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/Nanoplot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/usr/local/lib/python2.7/site-packages/nanoplot/NanoPlot.py", line 24, in <module>
    import nanoplotter
  File "/usr/local/lib/python2.7/site-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter import *
  File "/usr/local/lib/python2.7/site-packages/nanoplotter/nanoplotter.py", line 41, in <module>
    from pauvre.marginplot import margin_plot
  File "/usr/local/lib/python2.7/site-packages/pauvre/marginplot.py", line 360
    file=stderr)
        ^`

I've pip updated numpy, pandas, and pip itself. I've also pip3 installed Nanoplot and I get the same errors. 

Any advice?

**Comment by wdecoster** [comment]
While that error message is incomplete I can already tell you that NanoPlot does not work on Python 2.7. 

> I've also pip3 installed Nanoplot 

Good, but did you also remove the broken python 2.7 version first?
