### ISSUE TITLE
Error when using bgzipped filed

### ISSUE THREAD

**Issue by wdecoster** [wdecoster/NanoPlot#120]
Upon using a bgzip compressed file the following error was returned:

```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wdecoster/anaconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/wdecoster/anaconda3/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/wdecoster/anaconda3/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 424, in process_fastq_plain
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 424, in <listcomp>
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 434, in extract_from_fastq
    for rec in SeqIO.parse(fq, "fastq"):
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 655, in parse
    for r in i:
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/QualityIO.py", line 1029, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/QualityIO.py", line 895, in FastqGeneralIterator
    line = handle_readline()
  File "/home/wdecoster/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wdecoster/anaconda3/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 63, in main
    barcoded=args.barcoded)
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 74, in get_input
    dfs=[out for out in executor.map(extration_function, files)],
  File "/home/wdecoster/anaconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 74, in <listcomp>
    dfs=[out for out in executor.map(extration_function, files)],
  File "/home/wdecoster/anaconda3/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/wdecoster/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/wdecoster/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/wdecoster/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Potentially because nanoget uses
        `return open(inputfq, 'r')`
which could use `rt`?

¯\_(ツ)_/¯
￼

**Comment by wdecoster** [comment]
fixed in NanoPlot v1.20.1
