### ISSUE TITLE
NanoPlot Won't run after install

### ISSUE THREAD

**Issue by peflanag** [wdecoster/NanoPlot#122]
Hi, 

I used the pip install command to install NanoPlot but it won't run. I'm running it on macOS 10.13.6
Any ideas?

Cheers,

Peter

<img width="1215" alt="screen shot 2019-02-26 at 10 13 32" src="https://user-images.githubusercontent.com/32863969/53405189-31424f00-39af-11e9-9ecf-2f67ec1ed50b.png">

**Comment by wdecoster** [comment]
Your pip install mentions python2.7, which is not supported (as mentioned in the [README](https://github.com/wdecoster/NanoPlot#installation)). You should uninstall NanoPlot which was installed under python2.7 and instead install with python 3:

`pip uninstall NanoPlot`
`pip3 install NanoPlot`

**Comment by peflanag** [comment]
Oh I didn't realise pip3 meant python 3. And was just about to say same about NanoFilt. Thanks so much for your help!

**Comment by wdecoster** [comment]
Glad to help, let me know if you encounter other issues. You may also have to change how your $PATH is configured, if pip3 doesn't help.

**Comment by peflanag** [comment]
Nope pip3 worked. Thanks again!

**Comment by David-Lee86** [comment]
Hi, I installed nanoplot with "pip3 install NanoPlot". However when I try to run it, I am getting the following error

/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py:57: DeprecationWarning: PILLOW_VERSION is deprecated and will be removed in a future release. Use __version__ instead.
  from PIL import PILLOW_VERSION
Traceback (most recent call last):
  File "/gpfs01/home/sbadg3/.local/bin/NanoPlot", line 5, in <module>
    from nanoplot.NanoPlot import main
  File "/gpfs01/home/sbadg3/.local/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 20, in <module>
    import nanoplot.utils as utils
  File "/gpfs01/home/sbadg3/.local/lib/python3.7/site-packages/nanoplot/utils.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2355, in <module>
    switch_backend(rcParams["backend"])
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 832, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 213, in switch_backend
    switch_backend("agg")
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/gpfs01/software/imaging/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 45, in <module>
    from PIL import Image
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: /software/imaging/miniconda3/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: Permission denied


Please help

**Comment by wdecoster** [comment]
Please don't ask question in older issues, especially if yours is not related to the original question. I have made a new issue for your problem: https://github.com/wdecoster/NanoPlot/issues/205
