### ISSUE TITLE
If you read this then NanoPlot has crashed :-(

### ISSUE THREAD

**Issue by taffners** [wdecoster/NanoPlot#131]
2019-04-11 15:40:56,629 NanoPlot 1.18.2 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['../raw_reads/minion/2019_04_08-Adel/albacore_fastq/workspace/pass/barcode01/fastq_runid_e548be8fee13dfeb12f4569286b5fb1c27dca7e9.fastq'], fastq_minimal=None, fastq_rich=None, font_scale=1, format='png', listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='../results/2019_04_08_Adel_nanopore/URMC_267_K_pne_barcode01/nanoplot', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=4, title=None, verbose=False)
2019-04-11 15:40:56,630 Python version is: 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)  [GCC 7.2.0]
2019-04-11 15:40:56,645 Nanoplotter: valid output format png
2019-04-11 15:40:56,661 Nanoget: Starting to collect statistics from plain fastq file.
2019-04-11 15:40:58,599 Reduced DataFrame memory usage from 0.02213287353515625Mb to 0.012910842895507812Mb
2019-04-11 15:40:58,614 Nanoget: Gathered all metrics of 967 reads
2019-04-11 15:40:58,748 Calculated statistics
2019-04-11 15:40:58,748 Using sequenced read lengths for plotting.
2019-04-11 15:40:58,748 Processed the reads, optionally filtered. 967 reads left
2019-04-11 15:40:58,750 Nanoplotter: Valid color #4CB391.
2019-04-11 15:40:58,751 Nanoplotter: Creating length plots for Read length.
2019-04-11 15:40:58,751 Nanoplotter: Using 967 reads maximum of 53182bp.
2019-04-11 15:41:01,648 Created length plots
2019-04-11 15:41:01,648 Nanoplotter: Creating Read lengths vs Average read quality plots using statistics from 967 reads.
2019-04-11 15:41:01,860 Unknown property height
Traceback (most recent call last):
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 92, in main
    plots = make_plots(datadf, settings)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 328, in make_plots
    plot_settings=plot_settings)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 138, in scatter
    joint_kws={"s": 1})
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/seaborn/axisgrid.py", line 2247, in jointplot
    grid.plot_joint(plt.scatter, **joint_kws)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/seaborn/axisgrid.py", line 1755, in plot_joint
    func(self.x, self.y, **kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3470, in scatter
    edgecolors=edgecolors, data=data, **kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4323, in scatter
    collection.update(kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/artist.py", line 888, in update
    for k, v in props.items()]
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/artist.py", line 888, in <listcomp>
    for k, v in props.items()]
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/artist.py", line 881, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property height

/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "

**Comment by wdecoster** [comment]
This looks like an outdated version of seaborn or matplotlib, or both. Did you install using pip or conda?

**Comment by wdecoster** [comment]
I'll close this due to lack of response. Please let me know if you cannot solve this issue by updating seaborn and/or matplotlib.
