### ISSUE TITLE
NanoPlot cannot find dynamic_histogram and it crashes

### ISSUE THREAD

**Issue by cihanerkut** [wdecoster/NanoPlot#152]
Hello,

I'm doing RNA-Seq with ONT MinION (direct cDNA sequencing). After I align my reads to the reference genome via minimap2, I want to look at QC plots with NanoPlot. It always crashes because `nanoplotter` has no attribute `dynamic_histogram`.

Here's the content of the log file:

```
2019-10-21 13:48:54,179 NanoPlot 1.27.0 started with arguments Namespace(N50=False, alength=False, bam=['/data/trimmed_sorted.bam'], barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=600, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='/results/QC', path='/results/QC/QC_full_length_bam_', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='QC_full_length_bam_', raw=True, readtype='1D', runtime_until=None, store=False, summary=None, threads=32, title='x', ubam=None, verbose=False)
2019-10-21 13:48:54,179 Python version is: 3.7.4 (default, Sep 12 2019, 12:12:46)  [GCC 8.2.0]
2019-10-21 13:48:54,181 Nanoplotter: valid output format png
2019-10-21 13:48:54,210 Nanoget: Starting to collect statistics from bam file /data/trimmed_sorted.bam.
2019-10-21 13:48:54,306 Nanoget: Bam file /trimmed_sorted.bam contains 5073651 mapped and 285097 unmapped reads.
2019-10-21 13:53:58,446 Nanoget: bam /data/trimmed_sorted.bam contains 3096001 primary alignments.
2019-10-21 13:54:02,814 Reduced DataFrame memory usage from 441.56440830230713Mb to 355.9396858215332Mb
2019-10-21 13:54:06,065 Nanoget: Gathered all metrics of 3096001 reads
2019-10-21 13:54:50,491 Calculated statistics
2019-10-21 13:54:50,493 Using sequenced read lengths for plotting.
2019-10-21 13:54:50,794 Nanoplotter: Valid color #4CB391.
2019-10-21 13:54:50,794 Nanoplotter: Valid colormap Greens.
2019-10-21 13:54:50,988 Nanoplotter: Creating length plots for Read length.
2019-10-21 13:54:50,990 Nanoplotter: Using 3096001 reads maximum of 120080bp.
2019-10-21 13:56:15,177 Created length plots
2019-10-21 13:56:15,684 Nanoplotter: Creating Read lengths vs Average read quality plots using statistics from 3096001 reads.
2019-10-21 13:57:08,916 Created LengthvsQual plot
2019-10-21 13:57:09,390 Nanoplotter: Creating Aligned read lengths vs Sequenced read length plots using statistics from 3096001 reads.
2019-10-21 13:57:59,600 Created AlignedLength vs Length plot.
2019-10-21 13:57:59,601 Nanoplotter: Creating Read mapping quality vs Average basecall quality plots using statistics from 3096001 reads.
2019-10-21 13:58:49,562 Created MapQvsBaseQ plot.
2019-10-21 13:58:50,058 Nanoplotter: Creating Read length vs Read mapping quality plots using statistics from 3096001 reads.
2019-10-21 13:59:37,371 Created Mapping quality vs read length plot.
2019-10-21 13:59:37,407 Nanoplotter: Creating Percent identity vs Average Base Quality plots using statistics from 3096001 reads.
2019-10-21 14:00:53,915 Created Percent ID vs Base quality plot.
2019-10-21 14:00:54,353 Nanoplotter: Creating Aligned read length vs Percent identity plots using statistics from 3096001 reads.
2019-10-21 14:02:01,617 module 'nanoplotter' has no attribute 'dynamic_histogram'
Traceback (most recent call last):
  File "/sw/software/nanopack/1.0.0-foss-2019a-Python-3.7.4/lib/python3.7/site-packages/NanoPlot-1.27.0-py3.7.egg/nanoplot/NanoPlot.py", line 95, in main
    plots = make_plots(datadf, settings)
  File "/sw/software/nanopack/1.0.0-foss-2019a-Python-3.7.4/lib/python3.7/site-packages/NanoPlot-1.27.0-py3.7.egg/nanoplot/NanoPlot.py", line 262, in make_plots
    plots.append(nanoplotter.dynamic_histogram(array=datadf["percentIdentity"],
AttributeError: module 'nanoplotter' has no attribute 'dynamic_histogram'
```

Am I perhaps missing a dependency? It's running on CentOS 7, Python 3.7.4, installed via EasyBuild.

Thank you very much.

**Comment by wdecoster** [comment]
Hi,

EasyBuild is not something I am familiar with, I don't know if that uses PyPI or conda for installation.
You do have the most recent version, so that's good.

Could you give me the output of the following commands?

`python -c "import nanoplotter ; print(nanoplotter.__file__)"`
`python -c "import nanoplotter ; print(nanoplotter.__version__)"`
`python -c "import nanoplotter ; print(dir(nanoplotter))"`

Thanks,
Wouter

**Comment by cihanerkut** [comment]
Hi Wouter,

Thanks for the quick response.

In this case EasyBuild used PyPI. Basically, there is a location for the common Python 3.7.4 installation. It has only pip, setuptools and wheel modules. Then nanopack and all its dependencies are installed into another location, but the main Python path is also added to PATH, so ```pip3 list``` outputs this:

```
Package         Version
--------------- -------
biopython       1.74
cycler          0.10.0
joypy           0.2.1
kiwisolver      1.1.0
mappy           2.17
matplotlib      3.1.1
NanoComp        1.9.2
NanoFilt        2.5.0
nanoget         1.9.0
NanoGUI         0.1.0
NanoLyse        1.1.0
nanomath        0.23.1
nanopack        1.0.0
NanoPlot        1.27.0
nanoplotter     1.10.0
NanoStat        1.1.2
numpy           1.17.2
pandas          0.25.1
parasail        1.1.17
patsy           0.5.1
pauvre          0.1.86
pip             19.2.3
plotly          4.1.1
psutil          5.6.3
pyparsing       2.4.2
pysam           0.15.3
python-dateutil 2.8.0
pytz            2019.2
retrying        1.3.3
scipy           1.3.1
seaborn         0.9.0
setuptools      41.2.0
six             1.12.0
statsmodels     0.10.1
wheel           0.33.6
```

The output of the commands you requested are here:

```
$ python3 -c "import nanoplotter; print(nanoplotter.__file__)"
/sw/software/nanopack/1.0.0-foss-2019a-Python-3.7.4/lib/python3.7/site-packages/nanoplotter-1.10.0-py3.7.egg/nanoplotter/__init__.py
```

```
$ python3 -c "import nanoplotter; print(nanoplotter.__version__)"
1.10.0
```

```
$ python3 -c "import nanoplotter; print(dir(nanoplotter))"
['Plot', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'check_valid_color', 'check_valid_colormap', 'check_valid_format', 'cm', 'contains_variance', 'length_plots', 'logging', 'margin_plot', 'mcolors', 'mpl', 'namedtuple', 'nanoplotter_main', 'np', 'pd', 'plot', 'plot_settings', 'plt', 'run_tests', 'scatter', 'sns', 'spatial_heatmap', 'sys', 'time_plots', 'timeplots', 'version', 'yield_by_minimal_length_plot']
```

Manually it's OK because until that point I get what I want, but I'm trying to wrap up the entire QC in a pipeline and because NanoPlotter fails at that step it collapses the entire pipeline. Or I have to remove ```set -o pipefail``` from the script, but I'm reluctant to do that.

**Comment by wdecoster** [comment]
Could you try uninstalling the nanoplotter module? Its code is part of NanoPlot so the separate module is no longer required

**Comment by wdecoster** [comment]
Do you have an update on this?

**Comment by cihanerkut** [comment]
Yes, it ran smoothly without the the error when I removed `nanoplotter` module.

**Comment by wdecoster** [comment]
Thanks for the update!
