### ISSUE TITLE
nanoplot installation 

### ISSUE THREAD

**Issue by sachingadakh** [wdecoster/NanoPlot#156]
Hello I installed NanoPlot as given in the instructions. However while running it, I am getting this following error. Any help would be appreciated. Thank you
 NanoPlot -h
Traceback (most recent call last):
  File "/home/sanskark/.pyenv/versions/3.7-dev/bin/NanoPlot", line 11, in <module>
    load_entry_point('NanoPlot==1.28.0', 'console_scripts', 'NanoPlot')()
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 20, in <module>
    import nanoplot.utils as utils
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/nanoplot/utils.py", line 9, in <module>
    import pandas as pd
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/core/api.py", line 24, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (  # noqa: F401
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 44, in <module>
    from pandas.core.frame import DataFrame
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/core/frame.py", line 88, in <module>
    from pandas.core.generic import NDFrame, _shared_docs
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/core/generic.py", line 70, in <module>
    from pandas.io.formats.format import DataFrameFormatter, format_percentiles
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/io/formats/format.py", line 48, in <module>
    from pandas.io.common import _expand_user, _stringify_path
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/pandas/io/common.py", line 3, in <module>
    import bz2
  File "/home/sanskark/.pyenv/versions/3.7-dev/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

**Comment by wdecoster** [comment]
Did you install with pip or conda? I see your error message mentions pyenv. I'm not sure what the influence of this is.

**Comment by sachingadakh** [comment]
I installed through pip within pyenv.

**Comment by wdecoster** [comment]
Yeah I'm not familiar with pyenv. Googling for pyenv and _bz2 brought me to https://github.com/pyenv/pyenv/wiki/Common-build-problems and https://stackoverflow.com/questions/12806122/missing-python-bz2-module/12806325 Could you try the solutions presented there, depending on your operating system?

**Comment by sachingadakh** [comment]
I solved by installing the latest version of python 3.7, earlier it was 3.7-dev which was causing problem.
The issue has been solved. Thank you for your response and help.
