### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by smf96** [wdecoster/NanoPlot#158]
Hello,

While trying to run Nanoplot --fastq-rich,  I received the following error message message from the log file:

2019-11-22 15:14:39,637 NanoPlot 1.24.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=['rel_6.fastq'], font_scale=1, format='png', listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='/scratch/smf1g18/19.10_Aim1_BioinformaticDevelopment/Jain_NA12878_data', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='Release6_ALL_', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=4, title=None, ubam=None, verbose=False)
2019-11-22 15:14:39,637 Python version is: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
2019-11-22 15:14:39,646 Nanoplotter: valid output format png
2019-11-22 15:14:39,767 Nanoget: Starting to collect statistics from rich fastq file.
2019-11-22 20:13:53,013 Reduced DataFrame memory usage from 3077.868392944336Mb to 1449.5502195358276Mb
2019-11-22 20:14:08,328 unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1505, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1529, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1507, in na_op
    result = masked_arith_op(x, y, op)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1026, in masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 64, in main
    barcoded=args.barcoded)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/nanoget/nanoget.py", line 76, in get_input
    datadf = calculate_start_time(datadf)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/nanoget/nanoget.py", line 126, in calculate_start_time
    df["start_time"] = df["time_arr"] - df["time_arr"].min()
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1583, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1533, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas/_libs/algos.pyx", line 690, in pandas._libs.algos.arrmap
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1533, in <lambda>
    lambda x: op(x, rvalues))
TypeError: unsupported operand type(s) for -: 'str' and 'str'

I am trying to produce a summary report for the publicly available fastqs from the Jain et al (2018) paper on the NA12878 genome. Can you explain what " TypeError: unsupported operand type(s) for -: 'str' and 'str' " means please?

Best wishes,

Sarah

**Comment by wdecoster** [comment]
Would it be possible to share the file you are working on?

**Comment by smf96** [comment]
I downloaded it with the link:
http://s3.amazonaws.com/nanopore-human-wgs/rel6/rel_6.fastq.gz

**Comment by wdecoster** [comment]
Thanks, I'll have a look. Note that there is no need to decompress your fastq file for NanoPlot.

**Comment by wdecoster** [comment]
I am still downloading the file at an unbelievable low speed but already looked at a few reads. It turns out the header specifies that the data was generated on 31 December 1473 (e.g. start_time=1473-12-31T00:05:05Z). I find that rather unlikely. And that is the cause of this error, as pandas/numpy do not consider that date [valid](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#datetime-units) for their `datetime64[ns]` format.

You can "solve" the error by `zcat rel_6.fastq.gz | sed 's/start_time=1473/start_time=2017/' | gzip > rel_6_with_fixed_date.fastq.gz`, or substitute 2017 for any other date within the range 1678-2262.

Please let me know if there is anything else I can help you with.

**Comment by smf96** [comment]
Hello,

Thank you for your swift reply last time, I used your commands and replaced the 1473 start time with 2017 then tried running nanoplot again. I have received this error message from the log file:

2019-11-28 09:23:25,169 NanoPlot 1.24.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=['rel_6_with_fixed_date.fastq.gz'], font_scale=1, format='png', listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='/scratch/smf1g18/19.10_Aim1_BioinformaticDevelopment/Jain_NA12878_data', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='Release6_ALL_', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=16, title=None, ubam=None, verbose=False)
2019-11-28 09:23:25,169 Python version is: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
2019-11-28 09:23:25,191 Nanoplotter: valid output format png
2019-11-28 09:23:25,364 Nanoget: Starting to collect statistics from rich fastq file.
2019-11-28 09:23:25,365 Nanoget: Decompressing gzipped fastq rel_6_with_fixed_date.fastq.gz
2019-11-28 14:43:14,985 Reduced DataFrame memory usage from 3077.868392944336Mb to 1449.5502195358276Mb
2019-11-28 14:43:30,655 unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1505, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1529, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1507, in na_op
    result = masked_arith_op(x, y, op)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1026, in masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 64, in main
    barcoded=args.barcoded)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/nanoget/nanoget.py", line 76, in get_input
    datadf = calculate_start_time(datadf)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/nanoget/nanoget.py", line 126, in calculate_start_time
    df["start_time"] = df["time_arr"] - df["time_arr"].min()
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1583, in wrapper
    result = safe_na_op(lvalues, rvalues)
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1533, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas/_libs/algos.pyx", line 690, in pandas._libs.algos.arrmap
  File "/home/smf1g18/.conda/envs/py3conda_env/lib/python3.7/site-packages/pandas/core/ops.py", line 1533, in <lambda>
    lambda x: op(x, rvalues))
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Any help is much appreciated!

**Comment by wdecoster** [comment]
It looks like the exact same error here. Maybe there are more wrong dates. Please do the following on your fastq file, and let me know what you get:

`zcat reads.fastq.gz | grep '^@' | tr ' ' '\n' | grep '^start_time' | cut -f1 -d'T' | sort -u`

**Comment by smf96** [comment]
Hello,

Yes you were right, the output is:
start_time=1475-12-31
start_time=1476-12-31
start_time=1477-01-01
start_time=1477-12-31
start_time=1478-01-01
start_time=1478-12-31
start_time=1479-01-01
start_time=1479-12-31
start_time=1480-12-31
start_time=1481-01-01
start_time=1481-01-02
start_time=1487-12-31
start_time=2017-03-02
start_time=2017-03-03
start_time=2017-03-04
start_time=2017-03-05
start_time=2017-03-06
start_time=2017-03-07
start_time=2017-03-08
start_time=2017-03-09
start_time=2017-03-10
start_time=2017-03-11
start_time=2017-03-12
start_time=2017-12-31

**Comment by wdecoster** [comment]
What a mess.

The sed took 10 hours? Whoa.

Also, I believe this dataset is from multiple runs. Therefore the time plots won't be informative at all. You could consider doing 

`zcat rel_6.fastq.gz | sed 's/start_time=14/start_time=20/' | gzip > rel_6_with_fixed_date.fastq.gz`

And then just discard the time plots.

Alternatively, what do you want to get from the `--fastq_rich` format? Perhaps just going with `--fastq` is easier.

**Comment by smf96** [comment]
Hello,

That worked perfect, thank you!

**Comment by wdecoster** [comment]
Good to hear!
