### ISSUE TITLE
NanoPlot crash with nanoporetech/pipeline-structural-variation

### ISSUE THREAD

**Issue by linkxuan7** [wdecoster/NanoPlot#162]
I am planning to call structural variation with nanoporetech/pipeline-structural-variation which requires conda and snakemake. I use an isolated conda environment and the pipeline requires snakemake to be >5.4.3. I installed NanoPlot via Pip; nanoplot installation did not work with conda because conda will downgrade snakemake.

Running Nanoplot -v (1.28.1) or snakemake -v (5.8.1) on bash returns the version without incident. 

When I tested snakemake according to the pipeline with "snakemake --use-conda -p all", it returned an error as below. Any help will be appreciated. Thank you!

(/gpfs/ysm/project/xiao_andrew/kl487/conda_envs/snakemake) [kl487@c13n01 pipeline-structural-variation-1.4.0]$ snakemake --use-conda -p all
Working directory: /gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/
Using {sample}/target.bed as target file
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       auto_read_support
        1       filter_region
        1       filter_vcf
        1       index_vcf
        1       nanoplot_qc
        1       reformat_vcf
        1       sort_vcf
        8

[Mon Dec  2 18:42:27 2019]
rule nanoplot_qc:
    input: my_sample/alignment/my_sample_minimap2.bam
    output: my_sample/qc
    jobid: 2
    wildcards: sample=my_sample

NanoPlot -t 1 --bam my_sample/alignment/my_sample_minimap2.bam --raw -o my_sample/qc -p my_sample_ --N50 --title my_sample --downsample 100000
Activating conda environment: /gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f

If you read this then NanoPlot has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 162, in process_bam
    with cfutures.ProcessPoolExecutor(max_workers=kwargs["threads"]) as executor:
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/process.py", line 394, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 61, in main
    huge=args.huge)
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/site-packages/nanoget/nanoget.py", line 90, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/site-packages/nanoget/nanoget.py", line 90, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: max_workers must be greater than 0
[Mon Dec  2 18:42:46 2019]
Error in rule nanoplot_qc:
    jobid: 2
    output: my_sample/qc
    conda-env: /gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/results/.snakemake/conda/f953068f
    shell:
        NanoPlot -t 1 --bam my_sample/alignment/my_sample_minimap2.bam --raw -o my_sample/qc -p my_sample_ --N50 --title my_sample --downsample 100000
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job nanoplot_qc since they might be corrupted:
my_sample/qc
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/ysm/project/xiao_andrew/kl487/Software/pipeline-structural-variation-1.4.0/.snakemake/log/2019-12-02T184226.937380.snakemake.log
(/gpfs/ysm/project/xiao_andrew/kl487/conda_envs/snakemake)

**Comment by wdecoster** [comment]
Thanks for reporting this!

I was able to replicate your issue. The problem was introduced in https://github.com/wdecoster/nanoget/commit/d73fb23ce64486b95dea1862c8d2cbd0c584092f, so it was quite recent :)
In the newest version of nanoget (v1.12.0; `pip install nanoget -U`) this should be fixed. 

Please let me know if you encounter other issues.

Wouter

**Comment by wdecoster** [comment]
I'll close this now, please let me know if it's not fixed!
