### ISSUE TITLE
File site-packages/pauvre/marginplot.py, line 335, in margin_plot elif kwargs["kmerdf"]: KeyError: 'kmerdf'

### ISSUE THREAD

**Issue by spock** [wdecoster/NanoPlot#164]
Hi,

thank you for a useful package!

When running as
```
NanoPlot --threads 32 --no-N50 \
--outdir NanoPlot_linear_outliers \
--summary sequencing_summary.txt \
--plots dot kde hex pauvre
```

I'm getting
```
Traceback (most recent call last):
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/bin/NanoPlot", line 6, in <module>
    sys.exit(nanoplot.NanoPlot.main())
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 85, in main
    plots = make_plots(datadf, settings)
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 341, in make_plots
    title=settings["title"])
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 234, in scatter
    QUIET=True)
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/pauvre/marginplot.py", line 335, in margin_plot
    elif kwargs["kmerdf"]:
KeyError: 'kmerdf'
```

Looking into the `marginplot.py`, I see that it expects either `plot_maxqual` or `kmerdf` arguments:
```
    # Set max and min viewing window for quality
    if kwargs["plot_maxqual"]:
        max_plot_qual = kwargs["plot_maxqual"]
    elif kwargs["kmerdf"]:
        max_plot_qual = np.ceil(df["numks"].median() * 2)
    else:
        max_plot_qual = max(np.ceil(df['meanQual']))
```

Looking at `nanoplotter.py`, it sets `plot_maxqual` to `None`, and doesn't set `kmerdf` at all:
```
        margin_plot(df=pd.DataFrame({"length": x, "meanQual": y}),
                    Y_AXES=False,
                    title=title or "Length vs Quality in Pauvre-style",
                    plot_maxlen=None,
                    plot_minlen=0,
                    plot_maxqual=None,
                    plot_minqual=0,
                    lengthbin=None,
                    qualbin=None,
                    BASENAME="whatever",
                    path=pauvre_plot.path,
                    fileform=[figformat],
                    dpi=600,
                    TRANSPARENT=True,
                    QUIET=True)
```

Only the `pauvre` plot isn't generated, everything else is.

I've installed using conda, into a dedicated environment:
```
$ conda list | grep -i nanoplot
nanoplot                  1.8.1                    py36_0    bioconda
nanoplotter               0.35.3                   py36_0    bioconda
```

I've ventured into this rabbit hole.

I was able to bypass the initial issue by adding `kmerdf=None` to the list of arguments passed to `margin_plot` from `nanoplotter.py`.

I then got another one:
```
Traceback (most recent call last):
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/bin/NanoPlot", line 6, in <module>
    sys.exit(nanoplot.NanoPlot.main())
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 85, in main
    plots = make_plots(datadf, settings)
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 341, in make_plots
    title=settings["title"])
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 235, in scatter
    QUIET=True)
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/pauvre/marginplot.py", line 395, in margin_plot
    no_timestamp = kwargs["no_timestamp"],
KeyError: 'no_timestamp'
```

Bypassed by setting this one to `False`, and got the next one:
```
Traceback (most recent call last):
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/bin/NanoPlot", line 6, in <module>
    sys.exit(nanoplot.NanoPlot.main())
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 85, in main
    plots = make_plots(datadf, settings)
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 341, in make_plots
    title=settings["title"])
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 236, in scatter
    no_timestamp=False)
  File "/gpfs/backup/users/home/spock/.conda/envs/nanoplot/lib/python3.6/site-packages/pauvre/marginplot.py", line 397, in margin_plot
    transparent=kwargs["TRANSPARENT"])
TypeError: print_images() got an unexpected keyword argument 'base_output_name'
```

I've stopped here, because this now looks like a mismatch in versions....

What is likely wrong with my setup?

**Comment by wdecoster** [comment]
Thanks for reporting this. The pauvre plot is a bit of a headache. It's code maintained by someone else, and it may have gotten out of sync. I have a branch (https://github.com/wdecoster/NanoPlot/tree/internalize_pauvre) in which I am taking the code for the pauvre plot and putting it inside my own tool to avoid issues like that, but it is not finished at the moment.

Could you check which version of pauvre you have installed?
`python -c "import pauvre ; print(pauvre.__version__)"`

Last time I checked v0.1.86 should work - and that's also the one which is explicitly pinned in the setup.py, but maybe you got a more recent one.

**Comment by wdecoster** [comment]
Could you let me know the version of pauvre you have on your system?

**Comment by spock** [comment]
Sorry for the long silence, took longish vacations. Will check and report back within the next few days.

**Comment by spock** [comment]
I did get a more recent one: `0.1923`.
`conda list` shows that it comes from the bioconda channel:
```
nanoget                   1.2.2                    py36_0    bioconda
nanomath                  0.23.1                     py_1    bioconda
nanoplot                  1.8.1                    py36_0    bioconda
nanoplotter               0.35.3                   py36_0    bioconda
pauvre                    0.1923                     py_0    bioconda
```

**Comment by wdecoster** [comment]
I see you are using NanoPlot v1.8.1. The latest version on bioconda is v1.28.2, and explicitly will make sure you get pauvre v0.1.86. Could you see if updating solves your problem?

**Comment by spock** [comment]
ugh, sorry for not coming back in time with my results, this year has been rather strange so far...

From what I remember, updating (back in January) did solve the problem for me.

**Comment by wdecoster** [comment]
>  this year has been rather strange so far...

Definitely. Thanks for the feedback!
