### ISSUE TITLE
'ValueError: Lengths of sequence and quality values differs' with NanoPlot 1.28.1 

### ISSUE THREAD

**Issue by zhixue** [wdecoster/NanoPlot#166]
Hello! @wdecoster 
Thanks for your work of NanoPlot!
I ran a batch of nanoplot samples with NanoPlot 1.28.1 (from conda) and some error happened when I merged the results.
Several samples failed with NanoPlot, with 'ValueError: Lengths of sequence and quality values differs'.  
I checked the issues and someone else had [the same problem](https://github.com/wdecoster/NanoPlot/issues/141). But the version of NanoPlot I used had been updated.
My command:
```bash
NanoPlot -t 4 --fastq ${file} -o xxxx/${sample} -p ${sample} --plots hex dot
```
The detailed log:
```
2019-12-26 10:54:17,445 NanoPlot 1.28.1 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['xxxxx/samplexxx.fq.gz'], fastq_minimal=None, fastq_rich=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='xxxxxx/samplexxxout', path='xxxxxx/samplexxxout'', percentqual=False, pickle=None, plots=['hex', 'dot'], prefix='TG62', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=4, title=None, ubam=None, verbose=False)
2019-12-26 10:54:17,447 Python version is: 3.7.5 (default, Oct 25 2019, 15:51:11)  [GCC 7.3.0]
2019-12-26 10:54:17,503 NanoPlot:  valid output format png
2019-12-26 10:54:17,911 Nanoget: Starting to collect statistics from plain fastq file.
2019-12-26 10:54:17,936 Nanoget: Decompressing gzipped fastq xxxxx/samplexxx.fq.gz
2019-12-26 11:17:13,375 Lengths of sequence and quality values differs  for d7a59d12-cb5a-4ebf-ac6c-7d47b238f40d runid=ea3f5853b9bda06c934c152846e4dc97af04add2 read=1109 ch=2490 start_time=2019-09-27T05:11:07Z flow_cell_id=PAE04314 protocol_group_id=basecalled sample_id=20190927-NPL1204-P1-PAE04314 barcode=barcode09 (14130 and 16901).
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 302, in process_fastq_plain
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 302, in <listcomp>
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 312, in extract_from_fastq
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 661, in parse
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 1027, in FastqPhredIterator
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 948, in FastqGeneralIterator
ValueError: Lengths of sequence and quality values differs  for d7a59d12-cb5a-4ebf-ac6c-7d47b238f40d runid=ea3f5853b9bda06c934c152846e4dc97af04add2 read=1109 ch=2490 start_time=2019-09-27T05:11:07Z flow_cell_id=PAE04314 protocol_group_id=basecalled sample_id=20190927-NPL1204-P1-PAE04314 barcode=barcode09 (14130 and 16901).
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 61, in main
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/nanoget/nanoget.py", line 90, in get_input
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/site-packages/nanoget/nanoget.py", line 90, in <listcomp>
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/concurrent/futures/_base.py", line 435, in result
  File "/lustre/home/acct-clswcc/clswcc-xhz/.conda/envs/bio/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
ValueError: Lengths of sequence and quality values differs  for d7a59d12-cb5a-4ebf-ac6c-7d47b238f40d runid=ea3f5853b9bda06c934c152846e4dc97af04add2 read=1109 ch=2490 start_time=2019-09-27T05:11:07Z flow_cell_id=PAE04314 protocol_group_id=basecalled sample_id=20190927-NPL1204-P1-PAE04314 barcode=barcode09 (14130 and 16901).
```

I got the basecalling passed fastq a few days ago. Is there something wrong with these fastq files? Could you give some suggestion? Thank you!

**Comment by wdecoster** [comment]
> Is there something wrong with these fastq files?

Yes. The error is from biopython, which I use to parse fastq files. It's not related to NanoPlot itself so changing the version doesn't make a difference. 

It explicitly tells you: Lengths of sequence and quality values differs  for d7a59d12-cb5a-4ebf-ac6c-7d47b238f40d runid=ea3f5853b9bda06c934c152846e4dc97af04add2 read=1109 ch=2490 start_time=2019-09-27T05:11:07Z flow_cell_id=PAE04314 protocol_group_id=basecalled sample_id=20190927-NPL1204-P1-PAE04314 barcode=barcode09 (14130 and 16901).

So check out that read. It's corrupted.

**Comment by iliasbukraa** [comment]
Hi @abeliavskaia, could you maybe provide the whole stack trace error so we can see whether NanoPlot crashes or if it's just an error by another package. At first sight it might look like the same error as before...

**Comment by wdecoster** [comment]
@abeliavskaia could you share that fastq file with me to have a look? The Biopython error reports the read is 655 nucleotides, and the quality string is 23052328995 characters (which seems highly unlikely).

Wouter
