### ISSUE TITLE
Nanoplot crashing

### ISSUE THREAD

**Issue by pc395** [wdecoster/NanoPlot#168]
Hi,
I recently tried to run nanoplot to analyze MinIon read data and I received the following error:

-Device:Desktop$ NanoPlot --prefix summ --summary sequencing_summary.txt -t 8

"The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
If you read this then NanoPlot has crashed :-(

Traceback (most recent call last):
  File "/Users/poonamchitale/anaconda/bin/NanoPlot", line 6, in <module>
    exit(main())
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 95, in main
    plots = make_plots(datadf, settings)
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 161, in make_plots
    plot_settings=plot_settings)
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 169, in scatter
    joint_kws={"s": 1})
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/seaborn/distributions.py", line 804, in jointplot
    grid.plot_joint(plt.scatter, **joint_kws)
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/seaborn/axisgrid.py", line 1727, in plot_joint
    func(self.x, self.y, **kwargs)
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2841, in scatter
    None else {}), **kwargs)
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/matplotlib/__init__.py", line 1599, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4500, in scatter
    collection.update(kwargs)
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/matplotlib/artist.py", line 974, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/matplotlib/artist.py", line 974, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/Users/poonamchitale/anaconda/lib/python3.6/site-packages/matplotlib/artist.py", line 970, in _update_property
    .format(type(self).__name__, k))
AttributeError: 'PathCollection' object has no property 'height'"

**Comment by wdecoster** [comment]
Could you let me know how you installed NanoPlot? With conda or pip?
Which version are you using? (`NanoPlot --version`). Based on the error message this is for sure not the most recent version... so please try again after updating.

**Comment by wdecoster** [comment]
Please try updating your NanoPlot installation, and open a new issue if the problem persists.

Thanks,
Wouter
