### ISSUE TITLE
orca required?

### ISSUE THREAD

**Issue by kapsakcj** [wdecoster/NanoPlot#174]
Hey Wouter, quick question for you. Is `orca` absolutely required for NanoPlot? If I don't install it, will it cause any major issues with the primary functionality of NanoPlot? I usually feed NanoPlot a `sequencing_summary.txt` to get the wonderful stats and plots that are in the html report.

I've built a docker image for NanoPlot where I install via pip with `pip3 install requests NanoPlot==1.27.0`, which doesn't install `orca` along with NanoPlot. Full dockerfile here: https://github.com/StaPH-B/docker-builds/blob/master/nanoplot/1.27.0/Dockerfile

NanoPlot seems to run fine, generating all the images, plots, and html report as expected but I do get an error message regarding orca not being installed. 

I ask because installing `orca` is a bit of a pain to install (I'd prefer not to put conda in the docker image), it requires `fuse` and I can't get it to play well with docker. Hoping to get by without it if possible :)

Best,
Curtis

**Comment by wdecoster** [comment]
Hi Curtis,

Thanks for the docker image! Did you get an actual error crashing the program, or did it simply print a warning? Because it should do the latter if it notices there is no orca installation.
Orca is used to generate a static image from the dynamic HTML images but is entirely optional.

Wouter

**Comment by kapsakcj** [comment]
ok great, thanks for confirming that for me. That will make my life a little bit easier :) Feel free to close this issue.

I plan on building an image for the latest nanoplot release and pushing to dockerhub today.

It does not crash and finishes running, but does produce some warnings and one python traceback:
```
...[removed for brevity]...
2020-03-17 19:05:46,487 NanoPlot:  Creating length plots for Read length.
2020-03-17 19:05:46,523 NanoPlot:  Using 5856408 reads maximum of 162524bp.
2020-03-17 19:05:54,229 Nanoplotter: orca not found, not creating static image of html. See https://github.com/plotly/orca
2020-03-17 19:05:54,229
The orca executable is required to export figures as static images,
but it could not be found on the system path.

Searched for executable 'orca' on the following path:
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca.

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nanoplotter/plot.py", line 60, in save_static
    pio.write_image(self.fig, self.path.replace('html', 'png'))
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1705, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1482, in to_image
    ensure_server()
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1344, in ensure_server
    validate_executable()
  File "/usr/local/lib/python3.5/dist-packages/plotly/io/_orca.py", line 1043, in validate_executable
    instructions=install_location_instructions,
ValueError:
The orca executable is required to export figures as static images,
but it could not be found on the system path.

Searched for executable 'orca' on the following path:
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca.

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python

2020-03-17 19:07:08,017 Created length plots
2020-03-17 19:07:08,506 NanoPlot:  Creating Read lengths vs Average read quality plots using statistics from 5856408 reads.
2020-03-17 19:08:25,646 Created LengthvsQual plot
2020-03-17 19:08:25,647 Nanoplotter: Creating heatmap of reads per channel using 5856408 reads.
2020-03-17 19:08:26,514 Created spatialheatmap for succesfull basecalls.
2020-03-17 19:08:27,537 Nanoplotter: Creating timeplots using 5856408 reads.
2020-03-17 19:09:24,245 Created timeplots.
2020-03-17 19:09:24,246 Writing html report.
2020-03-17 19:11:21,888 Finished!
```

**Comment by wdecoster** [comment]
Ah that's all fine, the error reported in the traceback is caught by NanoPlot and just in the log file, without getting actually raised.

**Comment by wdecoster** [comment]
FYI: From v1.33.0 orca is no longer required for static images and NanoPlot/NanoComp use Kaleido (https://github.com/plotly/Kaleido).

**Comment by kapsakcj** [comment]
thanks for the heads up. Kaleido looks to be compatible with the docker image base that I typically use, ubuntu, so this looks promising. https://github.com/plotly/Kaleido#docker-compatibility

When I'm able I'll make a new docker image for the latest NanoPlot.

**Comment by wdecoster** [comment]
Thanks!
