### ISSUE TITLE
Novice - problems installing

### ISSUE THREAD

**Issue by os103** [wdecoster/NanoPlot#176]
Hi, 

I'm having trouble using NanoPlot after installing with Nanopack. I am able to use NanoStat through this method. 

Installation by `pip install nanopack`

When I try to use NanoPlot I get the error copied below. I am new to command line and newer still to Python so apologies in advance if this is a simple mistake or something entirely unrelated to NanoPlot. 

Thanks!

`os103-python_env[os103@spectre12 apps]$ NanoPlot 
Traceback (most recent call last):
  File "/home/o/os103/.local/bin/NanoPlot", line 5, in <module>
    from nanoplot.NanoPlot import main
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 24, in <module>
    import nanoplotter
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter_main import *
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 32, in <module>
    from nanoplotter.plot import Plot
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplotter/plot.py", line 1, in <module>
    import plotly.io as pio
  File "/home/o/os103/.local/lib/python3.6/site-packages/plotly/__init__.py", line 30, in <module>
    from plotly import (
  File "/home/o/os103/.local/lib/python3.6/site-packages/plotly/graph_objs/__init__.py", line 100291, in <module>
    import ipywidgets
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/ipywidgets/__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 91, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 134, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pygments/styles/__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pygments/plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
    declare_namespace(pkg)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'`

**Comment by wdecoster** [comment]
Ah, it's perfectly possible that the NanoPack installation route was a bit outdated, and as such caused your error. Although I'm a bit confused by some parts of the error message, let us see if it goes away by updating. I will make NanoPack v1.0.2, which contains all the latest versions, available on PyPI. I just have to wait a bit as it seems the PyPI server is having issues... 

I'll confirm later, but when uploaded successfully you can then upgrade with `pip install nanopack -U`

 Please let me know if that helps!

**Comment by os103** [comment]
Thank you! I'll let you know.

**Comment by wdecoster** [comment]
NanoPack v1.0.2 should be available now!

**Comment by os103** [comment]
I now get the following error after upgrading with pip 

`os103-python_env[os103@spectre11 apps]$ pip install nanopack --upgrade
Collecting nanopack
  Downloading nanopack-1.0.2.tar.gz (2.7 kB)
Requirement already satisfied, skipping upgrade: NanoPlot>=1.29.0 in /lustre/ahome3/o/os103/.local/lib/python3.6/site-packages (from nanopack) (1.29.0)
Collecting NanoStat>=1.2.0
  Downloading NanoStat-1.2.0.tar.gz (5.6 kB)
Requirement already satisfied, skipping upgrade: NanoFilt>=2.6.0 in /lustre/ahome3/o/os103/.local/lib/python3.6/site-packages (from nanopack) (2.6.0)
Requirement already satisfied, skipping upgrade: NanoLyse>=1.1.0 in /lustre/ahome3/o/os103/.local/lib/python3.6/site-packages (from nanopack) (1.1.0)
ERROR: Could not find a version that satisfies the requirement nanoget>=1.21.1 (from nanopack) (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.10.0, 0.10.1, 0.10.6, 0.11.0, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.7, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.16.1, 0.17.0, 0.18.0, 0.19.0, 0.19.3, 1.0.0, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.5.0, 1.5.2, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.8.0, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.12.0, 1.12.1)
ERROR: No matching distribution found for nanoget>=1.21.1 (from nanopack)`

I also get what looks like the same error when calling NanoPlot.

`os103-python_env[os103@spectre11 apps]$ NanoPlot
Traceback (most recent call last):
  File "/home/o/os103/.local/bin/NanoPlot", line 5, in <module>
    from nanoplot.NanoPlot import main
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 24, in <module>
    import nanoplotter
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter_main import *
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 32, in <module>
    from nanoplotter.plot import Plot
  File "/home/o/os103/.local/lib/python3.6/site-packages/nanoplotter/plot.py", line 1, in <module>
    import plotly.io as pio
  File "/home/o/os103/.local/lib/python3.6/site-packages/plotly/__init__.py", line 30, in <module>
    from plotly import (
  File "/home/o/os103/.local/lib/python3.6/site-packages/plotly/graph_objs/__init__.py", line 100291, in <module>
    import ipywidgets
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/ipywidgets/__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 91, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 134, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pygments/styles/__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pygments/plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
    declare_namespace(pkg)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/cm/shared/apps/python/gcc/3.6.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'`

Thanks for your help!

**Comment by wdecoster** [comment]
Could you try:

pip uninstall nanoplotter
pip install NanoPlot --upgrade

**Comment by wdecoster** [comment]
With nanopack I made a stupid error, I wrote about nanoget 1.21.1 which should have been 1.12.1... :) Now there is a nanopack 1.0.3 which should be corrected

**Comment by os103** [comment]
Thank you! Looks like it's working now!

**Comment by wdecoster** [comment]
Good to hear, let me know if there is anything else I can help with
