### ISSUE TITLE
Dtype error

### ISSUE THREAD

**Issue by tauanajc** [wdecoster/NanoPlot#178]
Hi there!

I am trying to run NanoPlot on some new ONT data but it fails. I ran the exact same command with the same version just a few months ago. I tried upgrading from 1.27 to 1.29, but the error is the same. Googling a bit it seems to be related to pandas? But I don't know how to fix it. Any help is appreciated, thanks!

Error:
…/lib/python3.6/concurrent/futures/process.py:175: DtypeWarning:
Columns (4,7,13,14) have mixed types. Specify dtype option on import or set low_memory=False.

Log file is:

2020-04-09 17:25:03,613 NanoPlot 1.29.0 started with arguments Namespace(N50=True, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, font_scale=1, format='pdf', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='../nanoplot', path='../nanoplot/sample', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='sample-', raw=False, readtype='1D', runtime_until=None, store=False, summary=['sequencing_summary.txt'], threads=8, title=None, ubam=None, verbose=False)
2020-04-09 17:25:03,614 Python version is: 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42)  [GCC 7.2.0]
2020-04-09 17:25:03,625 NanoPlot:  valid output format pdf
2020-04-09 17:25:03,660 Nanoget: Collecting metrics from summary file sequencing_summary.txt for 1D sequencing
2020-04-09 17:25:05,887 Nanoget: Finished collecting statistics from summary file sequencing_summary.txt
2020-04-09 17:25:12,807 Reduced DataFrame memory usage from 268.90346240997314Mb to 261.9162607192993Mb
2020-04-09 17:25:14,267 Nanoget: Gathered all metrics of 1831653 reads
2020-04-09 17:25:14,403 must be str, not int
Traceback (most recent call last):
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 73, in main
    settings["statsfile"] = [make_stats(datadf, settings, suffix="")]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 113, in make_stats
    outputfile=statsfile)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 142, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 142, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 30, in __init__
    self.number_of_bases = np.sum(df["lengths"])
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2076, in sum
    initial=initial)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 84, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/pandas/core/generic.py", line 11585, in stat_func
    min_count=min_count,
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/pandas/core/series.py", line 4087, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/pandas/core/nanops.py", line 70, in _f
    return f(*args, **kwargs)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/pandas/core/nanops.py", line 502, in nansum
    the_sum = values.sum(axis, dtype=dtype_sum)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/numpy/core/_methods.py", line 36, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial)
TypeError: must be str, not int

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting, would it be possible to share that sequencing_summary file for me to dig into this?

Cheers,
Wouter

**Comment by tauanajc** [comment]
Attachment available until May 10, 2020
Thanks for the quick reply Wouter,

Here it goes.

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAfQrwQ_sGgysJ3c0sVHW82_qIIinATHxkIpFDAd_3BtIYrq3yQKXBVmi%2F%24%7Bf%7D%3Fo%3DAleqdGw1sroRPI9ZEpipZhwOX4sPeg9JGL9FAj5ihS57%26v%3D1%26x%3D3%26a%3DCAogyb4bLQHHbZjdTKMA9UdJaleHPNVkkKnNa7zDJqbtZyESJxDXpf6lli4Y17X5-Z8uIgEAKggByAD_U64yA1IE6iCIp1oElwVZog%26e%3D1589125208%26k%3D%24%7Buk%7D%26fl%3D%26r%3DB94B5D40-7CBB-4C42-BE68-5ED7AA64D3CF-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D461EFA41-82FA-41A7-A007-3863DF836A97%26p%3D12%26s%3DBO4eQdxDirwFklxkNOZbOcGPJqo&uk=5M1H4yPhc_9SNC-MxnLysw&f=sequencing_summary.txt&sz=460668246>sequencing_summary.txt
460.7 MB

__

Tauana Junqueira Cunha
Postdoctoral Fellow
Smithsonian Tropical Research Institute
http://tauanacunha.com <http://tauanacunha.com/>

**Comment by wdecoster** [comment]
I get the impression there is something wrong with the summary file, if you grep for fd96e7dd-7116-4351-a0a6-dd1319abef81 you'll find a corrupted line. Use `grep -C2` to see two lines above and under the suspicious line to compare.

**Comment by tauanajc** [comment]
Attachment available until May 10, 2020
Hi Wouter,

You are right, it looks weird. Have you ever seen this?
I am running Nanoplot though the other folders/samples I have. It was successful in other 2, and failed with a similar but not identical error in another, which I copy below. I am still trying on others. Please let me know if you have any thoughts on what this could be related to. I base called the data with the exact same settings, the same day.

For now I guess my best hope is to try to baseball again?
Thanks for your time.

/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/concurrent/futures/process.py:175: DtypeWarning:

Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.

/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning:

Invalid value encountered in median

/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py:59: RuntimeWarning:

invalid value encountered in greater_equal




If you read this then NanoPlot 1.29.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues <https://github.com/wdecoster/NanoPlot/issues>
If you could include the log file that would be really helpful.
Thanks!



Traceback (most recent call last):
  File "/n/home00/tauanajc/.conda/envs/genomes/bin/NanoPlot", line 6, in <module>
    exit(main())
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 73, in main
    settings["statsfile"] = [make_stats(datadf, settings, suffix="")]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 113, in make_stats
    outputfile=statsfile)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 142, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 142, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 35, in __init__
    self.n50 = get_N50(np.sort(df["lengths"]))
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 59, in get_N50
    return readlengths[np.where(np.cumsum(readlengths) >= 0.5 * np.sum(readlengths))[0][0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAYel3L_9QxDWSyV2vJd64MdDZibsAc6tVnGLSSTlcU8oHx2HAN4xmxzz%2F%24%7Bf%7D%3Fo%3DAmr4raJNtjHOB7rwputbAFZ28fa-uiJvfgG4OEygitjX%26v%3D1%26x%3D3%26a%3DCAogCa8MBHNBv_7dg2OSpepBl8WpgHDjfElG2I8508QStYoSJxCz77izli4Ys_-zh6AuIgEAKggByAD_Ut54h1IEQ2Ym7FoEMZsc8w%26e%3D1589153431%26k%3D%24%7Buk%7D%26fl%3D%26r%3D02D125A3-11B1-4C5A-AAC9-1614ABFE17B2-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D461EFA41-82FA-41A7-A007-3863DF836A97%26p%3D12%26s%3DC5odPgYVcwUdCaSFhwfYZXewodI&uk=htIiFIxysHNWSuf2iz0Hpg&f=sequencing_summary.txt&sz=552640212>sequencing_summary.txt
552.6 MB

__

Tauana Junqueira Cunha
Postdoctoral Fellow
Smithsonian Tropical Research Institute
http://tauanacunha.com <http://tauanacunha.com/>

**Comment by tauanajc** [comment]
HI again,
Sorry for the multiple emails.
I just realized something, the only datasets that are failing/have issues in the sequencing_summary files, are the ones I base called from multiple flow cell folders. That is, I had two or more flow cells, and I set up guppy jobs at the same time, writing in the same folder. I am guessing that was the source of line errors in the sequencing file. 
Have you done this before?
I might try to basecall again sequentially, still saving to the same folder, I hope that works. Otherwise will have to figure something out about joining the fast5 files first, then calling guppy.
If you have a suggestion, please let me know.

And thanks again for the help!

**Comment by tauanajc** [comment]
Attachment available until May 10, 2020
Hi Wouter,

You are right, it looks weird. Have you ever seen this?
I am running Nanoplot though the other folders/samples I have. It was successful in other 2, and failed with a similar but not identical error in another, which I copy below. I am still trying on others. Please let me know if you have any thoughts on what this could be related to. I base called the data with the exact same settings, the same day.

For now I guess my best hope is to try to baseball again?
Thanks for your time.

/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/concurrent/futures/process.py:175: DtypeWarning:

Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.

/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning:

Invalid value encountered in median

/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py:59: RuntimeWarning:

invalid value encountered in greater_equal




If you read this then NanoPlot 1.29.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues <https://github.com/wdecoster/NanoPlot/issues>
If you could include the log file that would be really helpful.
Thanks!



Traceback (most recent call last):
  File "/n/home00/tauanajc/.conda/envs/genomes/bin/NanoPlot", line 6, in <module>
    exit(main())
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 73, in main
    settings["statsfile"] = [make_stats(datadf, settings, suffix="")]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 113, in make_stats
    outputfile=statsfile)
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 142, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 142, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 35, in __init__
    self.n50 = get_N50(np.sort(df["lengths"]))
  File "/n/home00/tauanajc/.conda/envs/genomes/lib/python3.6/site-packages/nanomath/nanomath.py", line 59, in get_N50
    return readlengths[np.where(np.cumsum(readlengths) >= 0.5 * np.sum(readlengths))[0][0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAYel3L_9QxDWSyV2vJd64MdDZibsAdfegEn39QoQU0ylB-3rT43dnLU7%2F%24%7Bf%7D%3Fo%3DAkNHpTrchKxJgh5ygu3znIxc75m7v-DnETecTrLYCpFd%26v%3D1%26x%3D3%26a%3DCAogW3dDX826umvBV5UROjUU2MSUx6wPJNqOOrGBMhJFwZMSJxDVkNSzli4Y1aDPh6AuIgEAKggByAD_Em5qnlIEQ2Ym7FoE3Zy1Ow%26e%3D1589153878%26k%3D%24%7Buk%7D%26fl%3D%26r%3D746C5912-1A76-4470-A1CD-448F36E05553-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D461EFA41-82FA-41A7-A007-3863DF836A97%26p%3D12%26s%3DB7V0RFA2FmV2c2DkbIGxmPP9sDE&uk=u_t9VVkcNEiJvKyf07-udA&f=sequencing_summary.txt&sz=552640212>sequencing_summary.txt
552.6 MB

__

Tauana Junqueira Cunha
Postdoctoral Fellow
Smithsonian Tropical Research Institute
http://tauanacunha.com <http://tauanacunha.com/>

**Comment by wdecoster** [comment]
> I just realized something, the only datasets that are failing/have issues in the sequencing_summary files, are the ones I base called from multiple flow cell folders. That is, I had two or more flow cells, and I set up guppy jobs at the same time, writing in the same folder. I am guessing that was the source of line errors in the sequencing file.
> Have you done this before?

That's very likely to be the cause, as multiple basecallers will then write to the same sequencing_summary file.
If you want to basecall in parallel as such I would suggest to each have their own output directory to avoid this.

> I might try to basecall again sequentially, still saving to the same folder, I hope that works. 
I think that when basecalling sequentially to the same folder guppy might actually overwrite the sequencing_summary file. So keep an eye on that, I don't know if it's going to append new records to the file.

> Otherwise will have to figure something out about joining the fast5 files first, then calling guppy.

You could check if the names of the fast5 files overlap, and if not just put them in the same directory.

**Comment by tauanajc** [comment]
Hi Wouter,

Indeed sequential base calling overwrites the sequencing_summary file. I created symlinks to the fast5 all in one folder and everything works fine now, just got the output of Nanoplot!

Thanks

**Comment by wdecoster** [comment]
Glad to hear that's solved, let me know if there is anything else I can help you with.
