### ISSUE TITLE
NanoPlot 1.30.0 has crashed :-(

### ISSUE THREAD

**Issue by unique379** [wdecoster/NanoPlot#186]
Hi
My bam qc has failed with some warnings and it's been suggested to report the issue. Please take a look logs as well as warnings written bellow. 

```
Apps/envs/NanoPacks/lib/python3.6/site-packages/matplotlib/contour.py:1171: RuntimeWarning:

invalid value encountered in greater

Apps/envs/NanoPacks/lib/python3.6/site-packages/seaborn/distributions.py:369: UserWarning:

Default bandwidth for data is 0; skipping density estimation.

Apps/envs/NanoPacks/lib/python3.6/site-packages/statsmodels/nonparametric/kernels.py:125: RuntimeWarning:

divide by zero encountered in true_divide

Apps/envs/NanoPacks/lib/python3.6/site-packages/matplotlib/contour.py:1520: UserWarning:

Warning: converting a masked element to nan.

Apps/envs/NanoPacks/lib/python3.6/site-packages/matplotlib/contour.py:1169: RuntimeWarning:

invalid value encountered in less

/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/NanoPacks/lib/python3.6/site-packages/matplotlib/contour.py:1171: RuntimeWarning:

invalid value encountered in greater

Apps/envs/NanoPacks/lib/python3.6/site-packages/seaborn/distributions.py:369: UserWarning:

Apps/envs/NanoPacks/lib/python3.6/site-packages/seaborn/axisgrid.py:1840: UserWarning:

JointGrid annotation is deprecated and will be removed in a future release.

If you read this then NanoPlot 1.30.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

Traceback (most recent call last):
  File "/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/NanoPacks/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/NanoPacks/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 97, in main
    plots = make_plots(datadf, settings)
  File "/stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/NanoPacks/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 316, in make_plots
    plots.append(nanoplotter.dynamic_histogram(array=datadf["percentIdentity"],
AttributeError: module 'nanoplotter' has no attribute 'dynamic_histogram'
[SID102054_cDNA_101819NanoPlot_20200608_1919.log]
```

**Attached LOG**
(https://github.com/wdecoster/NanoPlot/files/4749232/SID102054_cDNA_101819NanoPlot_20200608_1919.log)

**Comment by wdecoster** [comment]
Thanks for reporting this. Did you install NanoPlot with conda or pip?

**Comment by wdecoster** [comment]
Do you have any follow up on this?
