### ISSUE TITLE
NanoPlot 1.29.1 has crashed :-(

### ISSUE THREAD

**Issue by ggrimes** [wdecoster/NanoPlot#187]
NanoPlot crashed when I run the command

NanoPlot -t 8 --summary ../../data/raw/data/sequencing_summary_PAE07938_a0ca6d96.txt --raw -o results/sample1/qc/ -p sample1_ --N50 --title sample1

NanoPlot Installed via conda
--log below--

If you read this then NanoPlot 1.29.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/gpfs/igmmfs01/eddie/software/nanopipe_env/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/gpfs/igmmfs01/eddie/software/nanopipe_env/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 96, in main
    plots = make_plots(datadf, settings)
  File "/gpfs/igmmfs01/eddie/software/nanopipe_env/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 197, in make_plots
    plot_settings=plot_settings)
  File "/gpfs/igmmfs01/eddie/software/nanopipe_env/lib/python3.6/site-packages/nanoplotter/timeplots.py", line 46, in time_plots
    color=color)
  File "/gpfs/igmmfs01/eddie/software/nanopipe_env/lib/python3.6/site-packages/nanoplotter/timeplots.py", line 238, in cumulative_yield
    scatter_kws={"s": 3})
  File "/gpfs/igmmfs01/eddie/software/nanopipe_env/lib/python3.6/site-packages/seaborn/regression.py", line 810, in regplot
    x_jitter, y_jitter, color, label)
  File "/gpfs/igmmfs01/eddie/tomlinson-CRC-promethion/software/nanopipe_env/lib/python3.6/site-packages/seaborn/regression.py", line 114, in __init__
    self.dropna("x", "y", "units", "x_partial", "y_partial")
  File "/gpfs/igmmfs01/eddie/software/nanopipe_env/lib/python3.6/site-packages/seaborn/regression.py", line 66, in dropna
    setattr(self, var, val[not_na])
IndexError: invalid index to scalar variable

---
Any help would be appreciated.

Thanks

Graeme

**Comment by wdecoster** [comment]
Thanks for reporting this, would it be possible to share that summary file so I can replicate the issue?

**Comment by ggrimes** [comment]
sure can I email it to you?

**Comment by wdecoster** [comment]
Yes please! decosterwouter@gmail.com

**Comment by wdecoster** [comment]
This turns out to be a problem coming from a NanoPlot dependency (seaborn), see also https://github.com/mwaskom/seaborn/issues/1949
Updating seaborn to v0.10.1 fixed the issue for me. Can you confirm?

**Comment by ggrimes** [comment]
Thanks that fixed it.
