### ISSUE TITLE
NanoPlot 1.31.0 has crashed :-(

### ISSUE THREAD

**Issue by nbargues** [wdecoster/NanoPlot#194]
Hi, I have this error when running this command (I have a conda version) : 
for bla in $fastqDir/*.gz ; do
r="$(basename -s ".fastq.gz" $bla)"
NanoPlot -t $Ncpu --fastq $bla -o $r-nanoplot ;
done

the log file : 

2020-08-05 08:35:55,789 NanoPlot 1.31.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['/mnt/datagenetique/ANALYSIS/NANOPORE/GEN/Human-Germline-Targeted/MUC1/MUC1-2060731967-03-08-2020/FASTQ/FAN46998.fastq.gz'], fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, no_supplementary=False, outdir='FAN46998-nanoplot', path='FAN46998-nanoplot/', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=18, title=None, ubam=None, verbose=False)
2020-08-05 08:35:55,790 Python version is: 3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0]
2020-08-05 08:35:55,820 NanoPlot:  valid output format png
2020-08-05 08:35:55,829 [Errno 13] Permission denied
Traceback (most recent call last):
  File "/opt/miniconda3/envs/gene/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 66, in main
    keep_supp=not(args.no_supplementary))
  File "/opt/miniconda3/envs/gene/lib/python3.7/site-packages/nanoget/nanoget.py", line 85, in get_input
    with cfutures.ProcessPoolExecutor(max_workers=filethreads) as executor:
  File "/opt/miniconda3/envs/gene/lib/python3.7/concurrent/futures/process.py", line 556, in __init__
    pending_work_items=self._pending_work_items)
  File "/opt/miniconda3/envs/gene/lib/python3.7/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/opt/miniconda3/envs/gene/lib/python3.7/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/opt/miniconda3/envs/gene/lib/python3.7/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/opt/miniconda3/envs/gene/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/opt/miniconda3/envs/gene/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied

**Comment by wdecoster** [comment]
Can you confirm that you have read permission for `/mnt/datagenetique/ANALYSIS/NANOPORE/GEN/Human-Germline-Targeted/MUC1/MUC1-2060731967-03-08-2020/FASTQ/FAN46998.fastq.gz`?

**Comment by nbargues** [comment]
I have just done chmod -R 777 on the file but nothing change

**Comment by wdecoster** [comment]
You mean you got the same error message again? Can you please show me an `ls -l /mnt/datagenetique/ANALYSIS/NANOPORE/GEN/Human-Germline-Targeted/MUC1/MUC1-2060731967-03-08-2020/FASTQ/FAN46998.fastq.gz`?

Since you have a log file it is not a permission problem with writing to the destination...

This seems similar to threads with https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied
Can you see what the permissions are for `/dev/shm`?

**Comment by nbargues** [comment]
for the file : -rwxrwxrwx

for /dev/shm : drwxr-xr-x 

Thanks for helping me

**Comment by wdecoster** [comment]
So it appears you have no write permission to `/dev/shm`. I don't know if you have sudo/root permission, but perhaps you could try this suggestion? https://stackoverflow.com/a/53742149/6631639

**Comment by nbargues** [comment]
Wow nice it works well now ! Thanks

**Comment by wdecoster** [comment]
Good to hear - never seen that error before and glad someone else on StackOverflow already solved it...
