### ISSUE TITLE
ValueError: 'vertices' must be a 2D list or array with shape Nx2

### ISSUE THREAD

**Issue by tang191024** [wdecoster/NanoPlot#195]
Hi!
First of all thanks for developing this tools.
Unfortunately I'm failing to run it and I am getting the following error dump:

Traceback (most recent call last):
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/bin/NanoPlot", line 6, in <module>
    from nanoplot.NanoPlot import main
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 20, in <module>
    import nanoplot.utils as utils
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/nanoplot/utils.py", line 9, in <module>
    import pandas as pd
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/core/api.py", line 24, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (  # noqa: F401
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 44, in <module>
    from pandas.core.frame import DataFrame
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/core/frame.py", line 115, in <module>
    from pandas.core.series import Series
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/core/series.py", line 84, in <module>
    import pandas.plotting
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/plotting/__init__.py", line 59, in <module>
    from pandas.plotting._core import (
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/plotting/_core.py", line 17, in <module>
    import pandas.plotting._matplotlib  # noqa
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/plotting/_matplotlib/__init__.py", line 3, in <module>
    from pandas.plotting._matplotlib.boxplot import (
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/plotting/_matplotlib/boxplot.py", line 14, in <module>
    from pandas.plotting._matplotlib.core import LinePlot, MPLPlot
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/plotting/_matplotlib/core.py", line 34, in <module>
    from pandas.plotting._matplotlib.tools import (
  File "/home/dq-lab/miniconda3/envs/ont_tutorial_sv/lib/python3.6/site-packages/pandas/plotting/_matplotlib/tools.py", line 5, in <module>
    import matplotlib.table
  File "/home/dq-lab/.local/lib/python3.6/site-packages/matplotlib/table.py", line 24, in <module>
    from .patches import Rectangle
  File "/home/dq-lab/.local/lib/python3.6/site-packages/matplotlib/patches.py", line 11, in <module>
    from . import artist, cbook, colors, docstring, lines as mlines, transforms
  File "/home/dq-lab/.local/lib/python3.6/site-packages/matplotlib/lines.py", line 16, in <module>
    from .markers import MarkerStyle
  File "/home/dq-lab/.local/lib/python3.6/site-packages/matplotlib/markers.py", line 162, in <module>
    _empty_path = Path(np.empty((0, 2)))
  File "/home/dq-lab/.local/lib/python3.6/site-packages/matplotlib/path.py", line 130, in __init__
    "'vertices' must be a 2D list or array with shape Nx2")
ValueError: 'vertices' must be a 2D list or array with shape Nx2

Any help would be appreciated.

Thanks!

**Comment by wdecoster** [comment]
This error seems to arise already before executing any code from NanoPlot itself, but when importing pandas, and derives all the way down to matplotlib. Odd.

Could you tell me how you installed NanoPlot? 
What do you get if you do the following:
```

python -c "import pandas ; print(pandas.__version__)"
python -c "import matplotlib ; print(matplotlib.__version__)"
```

**Comment by tang191024** [comment]
Thanks for reply！
I install Nanoplot by "conda install nanoplot==1.28.2". But i have upgrade it to 1.31.0 by "pip install nanoplot -U"
Now,when i run command:python -c "import pandas ; print(pandas.__version__)" i get "1.1.0"
and "3.3.0" when Executing python -c "import matplotlib ; print(matplotlib.__version__)".

**Comment by wdecoster** [comment]
It's generally not recommended to install with conda and upgrade with pip, or vice versa. If you use conda to install then you probably should use conda to upgrade as well.
I'm not sure if that is the cause, but to exclude that could you uninstall with pip, check the version of NanoPlot again and see if it works? After that you can upgrade with conda...
