### ISSUE TITLE
pauvre error

### ISSUE THREAD

**Issue by procho** [wdecoster/NanoPlot#197]
Here's what I ran and the output. Log file attached.
I installed from bioconda channel a few hours ago, so I assume this is the latest version.
Thanks for taking a look at the error!
Best wishes
Simon

NanoPlot -t 5 --summary CIPF015_sequencing_summary_FAO33100_311f1b0f.txt -o CIPF015_nanoplots --loglength --N50 --plots dot kde hex pauvre
/Users/sprochnik/miniconda3/lib/python3.6/_collections_abc.py:841: MatplotlibDeprecationWarning:

The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.

If you read this then NanoPlot 1.31.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/Users/sprochnik/miniconda3/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/Users/sprochnik/miniconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 100, in main
    plots = make_plots(datadf, settings)
  File "/Users/sprochnik/miniconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 166, in make_plots
    plot_settings=plot_settings)
  File "/Users/sprochnik/miniconda3/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 236, in scatter
    QUIET=True)
  File "/Users/sprochnik/miniconda3/lib/python3.6/site-packages/pauvre/marginplot.py", line 335, in margin_plot
    elif kwargs["kmerdf"]:
KeyError: 'kmerdf'
[NanoPlot_20200817_1022.log](https://github.com/wdecoster/NanoPlot/files/5085837/NanoPlot_20200817_1022.log)

**Comment by wdecoster** [comment]
The NanoPlot version looks okay, but could you take a look at which pauvre version you have?

I think you will get that with `python -c "import pauvre ; print(pauvre.__version__)"`

**Comment by wdecoster** [comment]
Probably duplicate of https://github.com/wdecoster/NanoPlot/issues/164

**Comment by procho** [comment]
Thanks so much 

>>> print(pauvre.__version__)
0.1924

**Comment by procho** [comment]
Great, thank you so much,
I'll take a look at #164

Best wishes
Simon

**Comment by wdecoster** [comment]
Please see if upgrading pauvre to 0.2.0 helps.

Thanks,
Wouter

**Comment by wdecoster** [comment]
Did that work?

**Comment by procho** [comment]
Dear Wouter,
Thanks for checking in! 
I don't see 0.2.0 in anaconda and I haven't had a chance to upgrade manually.
I don't need it for now.
Best wishes
Simon

**Comment by macieksk** [comment]
Hi,

The following setup from conda with `pauvre=0.2.2` still experiences the same error, but

```yaml
name: nanoplot_1320
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - nanoplot=1.32.0
  - matplotlib 
  - pauvre=0.2.2 
  - psutil
  - requests
  - poppler
```
```bash
 $ conda list | grep 'pauvre\|matplotlib\|nanoplot'
matplotlib                3.3.1                         1    conda-forge
matplotlib-base           3.3.1            py37hd478181_1    conda-forge
nanoplot                  1.32.0                     py_0    bioconda
pauvre                    0.2.2                      py_0    bioconda
```

The error when `pauvre` plot is enabled:
```bash
2020-09-04 11:39:49,968 Created length plots
2020-09-04 11:39:50,893 NanoPlot:  Creating Read lengths vs Average read quality plots using statistics from 11497084 reads.
2020-09-04 11:40:04,331 Created length plots
2020-09-04 11:40:05,303 NanoPlot:  Creating Read lengths vs Average read quality plots using statistics from 11497084 reads.
2020-09-04 11:40:12,043 'kmerdf'
Traceback (most recent call last):
  File "/mnt/zgmvol/Bams/00genXone_samples/20-08-26_ONT/Project_translokacje/Sample_genxone_poznan_translokacje_servdna_s20034_gorka_kp365_PR002_S
LSK109/.snakemake/conda/134219d9/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "/mnt/zgmvol/Bams/00genXone_samples/20-08-26_ONT/Project_translokacje/Sample_genxone_poznan_translokacje_servdna_s20034_gorka_kp365_PR002_S
LSK109/.snakemake/conda/134219d9/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 169, in make_plots
    plot_settings=plot_settings)
  File "/mnt/zgmvol/Bams/00genXone_samples/20-08-26_ONT/Project_translokacje/Sample_genxone_poznan_translokacje_servdna_s20034_gorka_kp365_PR002_S
LSK109/.snakemake/conda/134219d9/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py", line 236, in scatter
    QUIET=True)
  File "/mnt/zgmvol/Bams/00genXone_samples/20-08-26_ONT/Project_translokacje/Sample_genxone_poznan_translokacje_servdna_s20034_gorka_kp365_PR002_S
LSK109/.snakemake/conda/134219d9/lib/python3.7/site-packages/pauvre/marginplot.py", line 335, in margin_plot
    elif kwargs["kmerdf"]:
KeyError: 'kmerdf'
```

**Comment by wdecoster** [comment]
I'll try to solve it, but right now the best way is to just avoid plots in the pauvre style.

**Comment by jenny315** [comment]
Hi,

The following setup  experiences the same error, and now what should I do to avoid plots in the pauvre style.
```bash
$ conda list | grep 'pauvre\|matplotlib\|nanoplot'
matplotlib                3.1.3                    pypi_0    pypi
nanoplot                  1.32.1                     py_0    bioconda
pauvre                    0.2                      pypi_0    pypi
```
Thanks for any advice!
Best wishes
Jenny

**Comment by wdecoster** [comment]
You will get the error only if you include pauvre with the --plots option. If you don't use --plots then everything is fine, the default is to not use pauvre.
