### ISSUE TITLE
text.latex.unicode is not a valid rc parameter

### ISSUE THREAD

**Issue by felixlee0608** [wdecoster/NanoPlot#204]
I need help!Thanks! command line as follows:

NanoPlot --fastq 20200722.pass.fastq.gz 20200724-.pass.fastq.gz -t 20 --plots kde hex dot pauvre -f pdf -o summary-plots-log-transformed-pass --N50 --title "Oxford Nanopore sequencing pass data statistics"

error log as follows:
2020-09-16 18:00:43,274 NanoPlot:  Creating Read lengths vs Average read quality plots using statistics from 1000 reads.
2020-09-16 18:00:49,594 'text.latex.unicode is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'
Traceback (most recent call last):
  File "~/biosoft/miniconda3/lib/python3.8/site-packages/matplotlib/__init__.py", line 677, in __setitem__
    cval = self.validate[key](val)
KeyError: 'text.latex.unicode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/biosoft/miniconda3/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "~/biosoft/miniconda3/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 160, in make_plots
    nanoplotter.scatter(
  File "~/biosoft/miniconda3/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 221, in scatter
    margin_plot(df=pd.DataFrame({"length": x, "meanQual": y}),
  File "~/biosoft/miniconda3/lib/python3.8/site-packages/pauvre/marginplot.py", line 197, in margin_plot
    rc.update_rcParams()
  File "~/biosoft/miniconda3/lib/python3.8/site-packages/pauvre/rcparams.py", line 7, in update_rcParams
    rcParams.update({
  File "~/biosoft/miniconda3/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "~/biosoft/miniconda3/lib/python3.8/site-packages/matplotlib/__init__.py", line 682, in __setitem__
    raise KeyError(
KeyError: 'text.latex.unicode is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'

**Comment by wdecoster** [comment]
Could you please try without the 'pauvre' plot?
