### ISSUE TITLE
NanoPlot crashed with the following et

### ISSUE THREAD

**Issue by AMTZ-ssi** [wdecoster/NanoPlot#206]
If you read this then NanoPlot 1.30.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/nanoget/extraction_functions.py", line 383, in process_fastq_rich
    for record in SeqIO.parse(inputfastq, "fastq"):
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 68, in __next__
    return next(self.records)
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/Bio/SeqIO/QualityIO.py", line 1081, in iterate
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/Bio/SeqIO/QualityIO.py", line 977, in FastqGeneralIterator
    raise ValueError(
ValueError: Lengths of sequence and quality values differs for 7045e61d-e2e6-4efc-9285-e9f908fbf8d6 runid=ed8ecd5ace06dcfdeb5f2318ba216a62f9b3bc24 read=6904 ch=121 start_time=2020-09-10T14:14:20Z flow_cell_id=FAN60354 protocol_group_id=BAAN_Ligation sample_id=BAAN_Ligation_1_200910 (2629 and 2529).
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/data/tools/public_envs/amtz_test_ont/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 55, in main
    datadf = get_input(
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/nanoget/nanoget.py", line 92, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/site-packages/nanoget/nanoget.py", line 92, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/srv/data/tools/public_envs/amtz_test_ont/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: Lengths of sequence and quality values differs for 7045e61d-e2e6-4efc-9285-e9f908fbf8d6 runid=ed8ecd5ace06dcfdeb5f2318ba216a62f9b3bc24 read=6904 ch=121 start_time=2020-09-10T14:14:20Z flow_cell_id=FAN60354 protocol_group_id=BAAN_Ligation sample_id=BAAN_Ligation_1_200910 (2629 and 2529).

**Comment by wdecoster** [comment]
More information would have been useful, but it looks like you are using fastq as input, and BioPython (a module which I use to parse fastq files) complains that the FASTQ record with ID 7045e61d-e2e6-4efc-9285-e9f908fbf8d6 is corrupted.
