### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'feather'

### ISSUE THREAD

**Issue by reemsami** [wdecoster/NanoPlot#215]
Hi there,

I am trying to run the Nanoplot python script on one of my bam files. I have the Nanoplot.py on the command shell line, and I ran the following:

$ `Python Nanoplot.py --bam file /PATH/sorted.bam`

And I get the following error message:

```
If you read this then NanoPlot 1.28.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!



Traceback (most recent call last):
  File "Nanoplot.py", line 392, in <module>
    main()
  File "Nanoplot.py", line 43, in main
    elif args.feather:
AttributeError: 'Namespace' object has no attribute 'feather'
```

The log file associated with it was:

```
2020-11-02 12:29:04,861 NanoPlot 1.28.1 started with arguments Namespace(N50=False, alength=False, bam=['file', '/PATH/sorted.bam'], barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='.', path='./', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=4, title=None, ubam=None, verbose=False)
2020-11-02 12:29:04,861 Python version is: 3.7.1 (default, Dec 14 2018, 19:28:38)  [GCC 7.3.0]
2020-11-02 12:29:04,885 NanoPlot:  valid output format png
2020-11-02 12:29:04,885 'Namespace' object has no attribute 'feather'
Traceback (most recent call last):
  File "Nanoplot.py", line 43, in main
    elif args.feather:
AttributeError: 'Namespace' object has no attribute 'feather'
```

Also, I can't use Nanplot to run the script without using "Python Nanoplot.py xxxx" as I get an error message that says:

`-bash: Nanoplot: command not found`

I have installed Nanoplot via SSH Secure Shell using pip and upgraded it to the newer version if that helps. 

Don't have that much experience with Python so I am not sure how to fix this. Would appreciate it if someone can help me out.

BW,

Reem

**Comment by wdecoster** [comment]
Hi Reem,

On which operating system did you install NanoPlot?

The `command not found` error is because the tool did not get installed in a location on your [$PATH](https://askubuntu.com/questions/551990/what-does-path-mean)

Wouter

**Comment by wdecoster** [comment]
Do you have any follow up on this?
