### ISSUE TITLE
AttributeError: 'PathCollection' object has no property 'stat_func'

### ISSUE THREAD

**Issue by jasmainelee** [wdecoster/NanoPlot#218]
Hi, 
I am trying to run the NanoPlot script on fastq files and recently installed all packages via miniconda. We now get the following error message:

/home/hisd/miniconda3/lib/python3.8/_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
/home/hisd/miniconda3/lib/python3.8/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
/home/hisd/miniconda3/lib/python3.8/site-packages/seaborn/distributions.py:2557: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)

If you read this then NanoPlot 1.32.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/home/hisd/miniconda3/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 160, in make_plots
    nanoplotter.scatter(
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 159, in scatter
    plot = sns.jointplot(
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/seaborn/axisgrid.py", line 2135, in jointplot
    grid.plot_joint(scatterplot, **joint_kws)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/seaborn/axisgrid.py", line 1734, in plot_joint
    func(x=self.x, y=self.y, **kwargs)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/seaborn/relational.py", line 820, in scatterplot
    p.plot(ax, kwargs)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/seaborn/relational.py", line 608, in plot
    scout = ax.scatter(scout_x, scout_y, **kws)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4498, in scatter
    collection.update(kwargs)
  File "/home/hisd/miniconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 996, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'PathCollection' object has no property 'stat_func'

Would appreciate if someone could help us out.

Thanks

**Comment by wdecoster** [comment]
This is a duplicate of https://github.com/wdecoster/NanoPlot/issues/201 (and is reported a few times now). Please downgrade your seaborn module to 0.10.1.

**Comment by jasmainelee** [comment]
Hi,

That worked. Thank you for your help! 

Do you know what this warning :"MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API." is about? Do I also need a specific version of Matplotlib?

Thanks

**Comment by wdecoster** [comment]
That's a harmless warning, and should not be visible anymore with more recent versions of NanoPlot. I'll update the one on bioconda, but you can just ignore it.

**Comment by jasmainelee** [comment]
Thank you!
