### ISSUE TITLE
ValueError: Transform failed with error code 1: Failed to serialize document: Uncaught

### ISSUE THREAD

**Issue by WeipengMO** [wdecoster/NanoPlot#219]
Hi Wouter,

When I run the Nanoplot with my `sequencing_summary.txt` file, I encountered the error. 

This is my command line:

```
NanoPlot \
  --threads 36 \
  --summary sequencing_summary.txt \
  --loglength \
  -o nanoplot
```

The log file is shown below:

```
2020-12-22 16:57:35,443 NanoPlot 1.33.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=True, maxlength=None, minlength=None, minqual=None, no_N50=False, no_supplementary=False, outdir='nanoplot', path='nanoplot/', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=['sequencing_summary.txt'], threads=32, title=None, tsv_stats=False, ubam=None, verbose=False)
2020-12-22 16:57:35,443 Python version is: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:46:49)  [GCC 7.5.0]
2020-12-22 16:57:35,445 NanoPlot:  valid output format png
2020-12-22 16:57:35,464 Nanoget: Collecting metrics from summary file sequencing_summary.txt for 1D sequencing
2020-12-22 16:57:49,689 Nanoget: Finished collecting statistics from summary file sequencing_summary.txt
2020-12-22 16:57:52,372 Reduced DataFrame memory usage from 629.3437957763672Mb to 340.8945560455322Mb
2020-12-22 16:57:54,987 Nanoget: Gathered all metrics of 13748225 reads
2020-12-22 16:58:04,311 Calculated statistics
2020-12-22 16:58:04,315 Using sequenced read lengths for plotting.
2020-12-22 16:58:04,886 Using log10 scaled read lengths.
2020-12-22 16:58:05,693 NanoPlot:  Valid color #4CB391.
2020-12-22 16:58:05,694 NanoPlot:  Valid colormap Greens.
2020-12-22 16:58:06,344 NanoPlot:  Creating length plots for Read length.
2020-12-22 16:58:06,359 NanoPlot:  Using 13748225 reads maximum of 91723bp.
2020-12-22 16:58:35,011 Transform failed with error code 1: Failed to serialize document: Uncaught
Traceback (most recent call last):
  File "/scem/work/mowp/miniconda3/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "/scem/work/mowp/miniconda3/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 155, in make_plots
    title=settings["title"])
  File "/scem/work/mowp/miniconda3/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py", line 324, in length_plots
    plots.append(dynamic_histogram(array=array, name=name, path=path, title=title, color=color))
  File "/scem/work/mowp/miniconda3/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py", line 347, in dynamic_histogram
    dynhist.save()
  File "/scem/work/mowp/miniconda3/lib/python3.7/site-packages/nanoplotter/plot.py", line 42, in save
    self.save_static()
  File "/scem/work/mowp/miniconda3/lib/python3.7/site-packages/nanoplotter/plot.py", line 60, in save_static
    f.write(scope.transform(self.fig, format="png"))
  File "/scem/work/mowp/miniconda3/lib/python3.7/site-packages/kaleido/scopes/plotly.py", line 112, in transform
    code=code, message=message
ValueError: Transform failed with error code 1: Failed to serialize document: Uncaught

``` 

I am appreciate it if you can help me out!

BW,
Weipeng

**Comment by wdecoster** [comment]
Since you closed this, can I assume it is solved?

**Comment by WeipengMO** [comment]
> Since you closed this, can I assume it is solved?

Yes. After updating to the 1.33.1 version, it solved.

Thanks!

**Comment by wdecoster** [comment]
Great to hear!
