### ISSUE TITLE
ValueError: `bins` should be a positive integer

### ISSUE THREAD

**Issue by jonbra** [wdecoster/NanoPlot#22]
Hi,

I am running NanoPlot on a Mac and installed it using pip3. I get the follwing error trying to plot on some fastq-files:

```
bio89093:~ jonbra$ NanoPlot --fastq /Users/jonbra/Dropbox/Prosjekter/Hydrurus/MinION/2017-10-17_Second_run/workspace/pass/fastq_runid_651403895f17581f06a733fbd7bcdf87c98f9b7c_0.fastq --loglength -o Desktop/
Fontconfig warning: ignoring UTF-8: not a valid region tag
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 61, in main
    make_plots(datadf, settings, args)
  File "/usr/local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 260, in make_plots
    log=settings["logBool"])
  File "/usr/local/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 284, in length_plots
    color=color)
  File "/usr/local/lib/python3.6/site-packages/seaborn/distributions.py", line 218, in distplot
    color=hist_color, **hist_kws)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6207, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 717, in histogram
    '`bins` should be a positive integer.')
ValueError: `bins` should be a positive integer.
bio89093:~ jonbra$
```

**Comment by wdecoster** [comment]
Hi jonbra,

Thank you for reporting this. It looks like insufficient testing was performed on a recent bit of code... My apologies! I'll have a look. Could you share the log file? I might find some clues in there.

Cheers,
Wouter

**Comment by jonbra** [comment]
Thanks for checking it out. How do I get the log file? Here I used `--verbose`, but that's probably not it?

```
bio89093:~ jonbra$ NanoPlot --verbose --fastq /Users/jonbra/Dropbox/Prosjekter/Hydrurus/MinION/2017-10-17_Second_run/workspace/pass/fastq_runid_651403895f17581f06a733fbd7bcdf87c98f9b7c_0.fastq --loglength -o Desktop/
Fontconfig warning: ignoring UTF-8: not a valid region tag
2017-10-31 14:40:14,497 NanoPlot 0.24.0 started with arguments Namespace(alength=False, bam=None, barcoded=False, color='#4CB391', downsample=None, drop_outliers=False, fastq=['/Users/jonbra/Dropbox/Prosjekter/Hydrurus/MinION/2017-10-17_Second_run/workspace/pass/fastq_runid_651403895f17581f06a733fbd7bcdf87c98f9b7c_0.fastq'], fastq_minimal=None, fastq_rich=None, format='png', listcolors=False, loglength=True, maxlength=None, minqual=None, outdir='Desktop/', plots=['kde', 'hex', 'dot'], prefix='', readtype='1D', summary=None, threads=4, verbose=True)
2017-10-31 14:40:14,497 Python version is: 3.6.3 (default, Oct  4 2017, 06:09:15)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
2017-10-31 14:40:14,497 Nanoplotter: valid output format png
2017-10-31 14:40:14,503 Nanoget: Starting to collect statistics from plain fastq file.
2017-10-31 14:40:14,606 Nanoget: Finished collecting statistics from plain fastq file.
2017-10-31 14:40:14,614 Nanoget: Gathered all metrics
2017-10-31 14:40:14,616 Calculated statistics
2017-10-31 14:40:14,616 Using sequenced read lengths for plotting.
2017-10-31 14:40:14,617 Using Log10 scaled read lengths.
2017-10-31 14:40:14,617 Processed the reads, optionally filtered. 268 reads left
2017-10-31 14:40:14,617 Nanoplotter: Valid color #4CB391.
2017-10-31 14:40:14,617 Nanoplotter: Creating length plots for Read length.
2017-10-31 14:40:14,618 Nanoplotter: Using 268 reads with read length N50 of 2121 and maximum of 4.038262407104784.
2017-10-31 14:40:14,737 `bins` should be a positive integer.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 61, in main
    make_plots(datadf, settings, args)
  File "/usr/local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 260, in make_plots
    log=settings["logBool"])
  File "/usr/local/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 284, in length_plots
    color=color)
  File "/usr/local/lib/python3.6/site-packages/seaborn/distributions.py", line 218, in distplot
    color=hist_color, **hist_kws)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6207, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 717, in histogram
    '`bins` should be a positive integer.')
ValueError: `bins` should be a positive integer.
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 61, in main
    make_plots(datadf, settings, args)
  File "/usr/local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 260, in make_plots
    log=settings["logBool"])
  File "/usr/local/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 284, in length_plots
    color=color)
  File "/usr/local/lib/python3.6/site-packages/seaborn/distributions.py", line 218, in distplot
    color=hist_color, **hist_kws)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6207, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 717, in histogram
    '`bins` should be a positive integer.')
ValueError: `bins` should be a positive integer.
bio89093:~ jonbra$
```

**Comment by wdecoster** [comment]
The log file is created in the output directory, so in your case on Desktop. But with --verbose you also get the same information printed to your console - so this suffices. I'll push a fix in a couple of seconds.

**Comment by wdecoster** [comment]
Updating the nanoplotter submodule to 0.20.1 should fix this!

`pip install nanoplotter -U`

or if that doesn't pull in the latest version

`pip install nanoplotter -U --no-cache-dir`

**Comment by jonbra** [comment]
`pip install nanoplotter -U` solved it!

**Comment by wdecoster** [comment]
Good to hear. Please let me know if you come across other issues or have suggestions/feature requests.
