### ISSUE TITLE
Error 'concurrent.futures.process._RemoteTraceback'

### ISSUE THREAD

**Issue by ieknot** [wdecoster/NanoPlot#223]
Hi Wouter,

I tried to run NanoPlot with fastq files, and it gave the following error:

`concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/tiboug/miniconda3/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/tiboug/miniconda3/lib/python3.7/concurrent/futures/process.py", line 191, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/Users/tiboug/miniconda3/lib/python3.7/concurrent/futures/process.py", line 191, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/tiboug/miniconda3/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 322, in process_fastq_plain
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/Users/tiboug/miniconda3/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 322, in <listcomp>
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/Users/tiboug/miniconda3/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 333, in extract_from_fastq
    yield nanomath.ave_qual(rec.letter_annotations["phred_quality"]), len(rec)
AttributeError: module 'nanomath' has no attribute 'ave_qual'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tiboug/miniconda3/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/Users/tiboug/miniconda3/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 66, in main
    keep_supp=not(args.no_supplementary))
  File "/Users/tiboug/miniconda3/lib/python3.7/site-packages/nanoget/nanoget.py", line 92, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/Users/tiboug/miniconda3/lib/python3.7/site-packages/nanoget/nanoget.py", line 92, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/Users/tiboug/miniconda3/lib/python3.7/concurrent/futures/process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/tiboug/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/Users/tiboug/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/tiboug/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: module 'nanomath' has no attribute 'ave_qual'`

I tried looking for an additional log file, but nothing was produced, I suspect because it didn't finished running anything. I was using v1.31.0, after getting the error message I updated to v 1.33.1, and then I got exactly the same error message. I saw there was a similar error (#206) where you suggested that there might be something wrong with a read ID, so I tried running it with 3 different fastq's (1.2 MB, 219MB and 3.3 MB in size). Unfortunately they all gave this error. Hope you can help! Thanks in advance.

**Comment by wdecoster** [comment]
Hi,

So sorry for that! It's definitely not a problem with your fastq files, but some incompatibility between the submodules you have installed. At some point I thought it was a pretty good idea to compartmentalize my code in multiple modules to more easily reuse functions, but then you get a mess like this when they're out of sync.

How did you install NanoPlot?
I think your nanoget module will be outdated, so if you could try updating that one...

Wouter

**Comment by ieknot** [comment]
Hi Wouter, thanks for your quick reply! I updated using pip: `pip install nanoget --upgrade`, and it fixed the problem! Thanks so much. I also recovered my log files, because I had made a typo which created the folders for output one level higher than I had intended to (oops, haha!). I've attached them for your reference, in case it's helpful.
All the best, Ineke

[NanoPlot_20210121_1409.log](https://github.com/wdecoster/NanoPlot/files/5854015/NanoPlot_20210121_1409.log)
[NanoPlot_20210121_1410.log](https://github.com/wdecoster/NanoPlot/files/5854016/NanoPlot_20210121_1410.log)
[NanoPlot_20210121_1425.log](https://github.com/wdecoster/NanoPlot/files/5854017/NanoPlot_20210121_1425.log)
[NanoPlot_20210121_1433.log](https://github.com/wdecoster/NanoPlot/files/5854018/NanoPlot_20210121_1433.log)
[NanoPlot_20210121_1436.log](https://github.com/wdecoster/NanoPlot/files/5854019/NanoPlot_20210121_1436.log)

**Comment by wdecoster** [comment]
Good to hear, thanks for the feedback!
