### ISSUE TITLE
Type error?

### ISSUE THREAD

**Issue by claumer** [wdecoster/NanoPlot#23]
Hi Wouter,

Looks like a really useful tool! But when I try to run it on our cluster, using python 3.5 and the bioconda installation route, I get the following error:

[claumer@ebi6-120 barcode08]$ NanoPlot -t 4 --fastq fastq_runid_f3842d5150d231bda407e98f5dfd3dbe63b6766a_0.fastq --maxlength 40000 --plots hex dot
Traceback (most recent call last):
  File "/nfs/research2/marioni/claumer/anaconda3/bin/NanoPlot", line 6, in <module>
    sys.exit(nanoplot.NanoPlot.main())
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 47, in main
    makePlots(datadf, lengthprefix, logBool, readlengthsPointer, args)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 216, in makePlots
    log=logBool)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/nanoplotter/nanoplotter.py", line 180, in lengthPlots
    kde_kws={"label": name, "clip": (0, maxvalx)})
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 220, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 642, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 269, in _univariate_kdeplot
    cumulative=cumulative)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 333, in _statsmodels_univariate_kde
    kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 146, in fit
    clip=clip, cut=cut)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 506, in kdensityfft
    f = revrt(zstar)
  File "/nfs/research2/marioni/claumer/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py", line 20, in revrt
    y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
TypeError: slice indices must be integers or None or have an __index__ method

Do you have any idea what might be going on? Happy to provide other details on my environment, installation, log files, etc.

Thanks kindly,
Chris L

**Comment by wdecoster** [comment]
This looks similar to https://github.com/wdecoster/NanoPlot/issues/21, can you try updating the statsmodels module?

**Comment by claumer** [comment]
My apologies, I had totally missed that -- you're quite right, that did the trick, and it seems to be working as expected now! Thanks for such a quick response.

**Comment by wdecoster** [comment]
Glad to hear it solved your problem. Unfortunately, it's not something I can fix, but I referenced this issue in the seaborn repo and perhaps we can figure out a way there to avoid this issue entirely. 

Anyway, thanks for reporting and please let me know if you come across other issues or have suggestions/feature requests.
