### ISSUE TITLE
ValueError: Invalid property specified for object of type plotly.graph_objs.layout.Annotation: 'textfont'

### ISSUE THREAD

**Issue by dl870** [wdecoster/NanoPlot#241]
Hi, 

I have installed NanoPlot with no issues, however when I try to run it I get the following error: 
(I have tried running it in an environment using python3 instead the 3.7 with no difference). 

If you read this then NanoPlot 1.35.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/opt/anaconda3/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 106, in main
    plots = make_plots(datadf, settings)
  File "/opt/anaconda3/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 163, in make_plots
    title=settings["title"])
  File "/opt/anaconda3/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py", line 407, in length_plots
    fig.add_annotation(text='N50', x=n50, y=0.95, textfont_size=8)
  File "/opt/anaconda3/lib/python3.7/site-packages/plotly/graph_objs/_figure.py", line 19001, in add_annotation
    **kwargs
  File "/opt/anaconda3/lib/python3.7/site-packages/plotly/graph_objs/layout/_annotation.py", line 2087, in __init__
    self._process_kwargs(**dict(arg, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/plotly/basedatatypes.py", line 4322, in _process_kwargs
    raise err
ValueError: Invalid property specified for object of type plotly.graph_objs.layout.Annotation: 'textfont'

Did you mean "font"?

    Valid properties:
(and then a list of valid properties)..

Thank you,

**Comment by wdecoster** [comment]
Thanks for reporting this and thanks to @iliasbukraa for the quick fix! This problem should be fixed in v1.35.1, which is now available on PyPI. Please let us know if you encounter other issues.

**Comment by dl870** [comment]
It works now, thank you so much!

**Comment by wdecoster** [comment]
Thanks for confirming!
