### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by guandailu** [wdecoster/NanoPlot#249]
Traceback (most recent call last):
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/94cba236/bin/NanoPlot", line 6, in <module>
    sys.exit(nanoplot.NanoPlot.main())
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/94cba236/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 61, in main
    nanomath.write_stats(datadf, settings["path"] + "NanoStats.txt")
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/94cba236/lib/python3.6/site-packages/nanomath/nanomath.py", line 177, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/94cba236/lib/python3.6/site-packages/nanomath/nanomath.py", line 177, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/.snakemake/conda/94cba236/lib/python3.6/site-packages/nanomath/nanomath.py", line 31, in __init__
    self.number_of_bases = np.sum(df["lengths"])
TypeError: string indices must be integers

**Comment by wdecoster** [comment]
Would it be very inconvenient to be a bit polite, as well as share some more information for me to figure out what is going on here?
