### ISSUE TITLE
TypeError: scatter() missing 1 required positional argument: 'data_frame'

### ISSUE THREAD

**Issue by ChiaWei-Liao** [wdecoster/NanoPlot#268]
Hello I just install the Nanoplot by

conda install -c bioconda nanoplot

I use NanoPlot for Nanopore .fastq examination.
command line as below:
NanoPlot -t 40 --fastq Dsph_barcode16.fastq -o Dsph_Nanoplot --loglength

But I got the error message like below:

If you read this then NanoPlot 1.38.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/home/jason/.local/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/home/jason/.local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 104, in main
    plots = make_plots(datadf, settings)
  File "/home/jason/.local/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 168, in make_plots
    figformat=settings["format"])
  File "/home/jason/.local/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 464, in length_plots
    figformat=figformat))
  File "/home/jason/.local/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 516, in yield_by_minimal_length_plot
    fig = px.scatter(x=df.reindex(idx)["lengths"], y=df.reindex(idx)["cumyield_gb"])
TypeError: scatter() missing 1 required positional argument: 'data_frame'

Here is the logfile:
[NanoPlot_20210802_1031.log](https://github.com/wdecoster/NanoPlot/files/6914072/NanoPlot_20210802_1031.log)

**Comment by wdecoster** [comment]
Thanks for reporting this! This is fixed in version 1.38.1, which will soon be available on PyPI and bioconda.
