### ISSUE TITLE
nanoplot Crush 

### ISSUE THREAD

**Issue by Fatihlrcfs** [wdecoster/NanoPlot#275]
Hi Dear,

I got an error during the Nanoplot run and it was crashed. I copied what was present on my screen and log file also. thanks 

(base) [2397405@login1 data]$ cd /cluster/lrcfs/ftiras/projects/nanopore_testing/data/First\ run\ 61\ years\ male/basecalledmodbase5mchac28x2/
(base) [2397405@login1 basecalledmodbase5mchac28x2]$ NanoPlot --summary sequencing_summary.txt --loglength -o summary-plots-log-transformed
/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/seaborn/distributions.py:2557: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)

If you read this then NanoPlot 1.32.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/cluster/lrcfs/ftiras/ftiras_env/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 160, in make_plots
    nanoplotter.scatter(
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 159, in scatter
    plot = sns.jointplot(
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/seaborn/axisgrid.py", line 2135, in jointplot
    grid.plot_joint(scatterplot, **joint_kws)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/seaborn/axisgrid.py", line 1734, in plot_joint
    func(x=self.x, y=self.y, **kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/seaborn/relational.py", line 820, in scatterplot
    p.plot(ax, kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/seaborn/relational.py", line 608, in plot
    scout = ax.scatter(scout_x, scout_y, **kws)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4597, in scatter
    collection.update(kwargs)
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/matplotlib/artist.py", line 1062, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'PathCollection' object has no property 'stat_func'
(base) [2397405@login1 basecalledmodbase5mchac28x2]$
Broadcast message from root@login1.compute.dundee.ac.uk (Mon 2021-10-18 17:00:00 BST):

Rebooting for system updates
The system is going down for reboot at Tue 2021-10-19 08:00:00 BST!

[NanoPlot_20211018_1655.log](https://github.com/wdecoster/NanoPlot/files/7366871/NanoPlot_20211018_1655.log)

**Comment by wdecoster** [comment]
Can you please post the output of `NanoPlot --version`. The current version is 1.38.1

**Comment by wdecoster** [comment]
Okay, and what is the version now?

**Comment by Fatihlrcfs** [comment]
the problem is still saying # All requested packages already installed. but there is no packages or files and says NanoPlot: command not found. Also, I checked the files virtually and there are no files for NanoPlot. Thanks
