### ISSUE TITLE
nanoplot crashes when trying to plot from summary file..

### ISSUE THREAD

**Issue by senidr** [wdecoster/NanoPlot#278]
NanoPlot --summary ~/DATA_RUNS/001_002_L1/001_002/20211026_1244_X2_FAR61006_eeaaba85/sequencing
_summary_FAR61006_c3669782.txt --loglength -o summary-plots-log-transformed

If you read this then NanoPlot 1.38.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/home/uqsidris/.local/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/home/uqsidris/.local/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 104, in main
    plots = make_plots(datadf, settings)
  File "/home/uqsidris/.local/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 161, in make_plots
    nanoplotter.length_plots(
  File "/home/uqsidris/.local/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 459, in length_plots
    plots.append(yield_by_minimal_length_plot(array=array,
  File "/home/uqsidris/.local/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 516, in yield_by_minimal_length_plot
    fig = px.scatter(df,x=df.reindex(idx)["lengths"], y=df.reindex(idx)["cumyield_gb"])
  File "/home/uqsidris/.local/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 52, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/home/uqsidris/.local/lib/python3.8/site-packages/plotly/express/_core.py", line 868, in make_figure
    trace_specs, grouped_mappings, sizeref, show_colorbar = infer_config(
  File "/home/uqsidris/.local/lib/python3.8/site-packages/plotly/express/_core.py", line 748, in infer_config
    raise ValueError(
ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['lengths', 'cumyield_gb'] but received: 189422     2901
153666     4632
20030     35185
132559     6625
27589     29771
          ...
38684     24803
156801     4372
128830     7036
114738     8685
125952     7360
Name: lengths, Length: 10000, dtype: uint64

**Comment by wdecoster** [comment]
Could you check the version of your plotly module? 
`python -c "import plotly ; print(plotly.__version__)"`
