### ISSUE TITLE
NanoPlot crashes

### ISSUE THREAD

**Issue by NiklasDreyer** [wdecoster/NanoPlot#280]
Hi,

Thanks for what appears to be an awesome program.

NanoPlot repeatedly crashes for me and I can't get any quality information out on my reads.

I can't locate the error and tried reinstalling and updating as well. Installed with conda and run in conda environment on macOS. 

Could I ask for some help understanding the error and a possible solution?
Best,
Niklas

### log file ### 
2021-11-12 17:42:26,910 NanoPlot 1.32.1 started with arguments Namespace(N50=True, alength=False, bam=None, barcoded=False, color='yellow', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['m54057_190926_040405.Q20.fastq'], fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=10000, minlength=50, minqual=None, no_N50=False, no_supplementary=False, outdir='/Users/niklasdreyer/Desktop/nanoplot', path='/Users/niklasdreyer/Desktop/nanoplot/plot', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='plot', raw=True, readtype='1D', runtime_until=None, store=False, summary=None, threads=2, title='CCS_raw_Q20_Facetotecta', tsv_stats=False, ubam=None, verbose=False)
2021-11-12 17:42:26,910 Python version is: 3.7.7 (default, Mar 26 2020, 10:32:53)  [Clang 4.0.1 (tags/RELEASE_401/final)]
2021-11-12 17:42:26,912 NanoPlot:  valid output format png
2021-11-12 17:42:26,939 Nanoget: Starting to collect statistics from plain fastq file.
2021-11-12 17:42:30,398 End of file without quality information.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 327, in process_fastq_plain
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 327, in <listcomp>
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoget/extraction_functions.py", line 337, in extract_from_fastq
    for rec in SeqIO.parse(fq, "fastq"):
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 73, in __next__
    return next(self.records)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 1080, in iterate
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 939, in FastqGeneralIterator
    raise ValueError("End of file without quality information.")
ValueError: End of file without quality information.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 66, in main
    keep_supp=not(args.no_supplementary))
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoget/nanoget.py", line 94, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoget/nanoget.py", line 94, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: End of file without quality information.

### exempt from the fastq file, which does not seem to be corrupt. Runs fine with other scripts ### 
@m54057_190926_040405/4194389/ccs
GCAATGAAGTCGCAGGGTTGGGATCAGTTGATTCTGACCAACCGTCCAGCACTCGACATGTTCCAGATCGTCCTCGTCGCCGCCCTCGTGGCCTCCGCTGCCGCCGCCAACACTGGCTACAGGGCCCCTTCATACGGCCATGCCGCCGCCCCCGCCTACGGAGGCCACCGTGCCGCCGGATACGGTTACGGCGCCGACTACTATGAGGAGCCCAACTACAACTACGAGTACGCCGTGAAGGACGACTACAGCGGCAACGACTTCGGCCAGACTGAGTACCGTGACGGATACAGCACCAAGGGATCCTACTCCGTCGCCCTCCCCGACGGCCGCACCCAGACCGTCACCTACGCCGATGATGGCTACGGTCTCGTTGCCGACGTCTCCTACTACGGCGAGGCCCGCTACGACAGCTACGGACACGGATATGCTGCCCCATCTTACGGCTACAAGGCCGCTCCCTCTTATGGCCATGCCCGTCCTTCCTACGGATACAAGGCTGCTCCTTCTTATGGATACAAGGCCGCTCCCTCTTACGGATACAGGGCTGCCGCTCCCTCTTACGGGTACAGGGCTGCCGCTCCTTCTTATGGCTACAGAGCCGCCCCCGCTTACGGATATAGCCGTCCCTCTTATGGATACAGCCGTCCCTCCTACGGATACGGATACAGCCGTCCTTCTTACGGATACAGAGCCGCTGCTCCCGCTTACGGCAAGCACTAAGTAGAGACATGAACAAACCCGTCTTCTTTCTTCTCTCATACCATCTGGCTATCGCAATTTGATTGTGCTCTCCTACTTTACCCATCCGCATTCAGCTCATTCCAACTTTCCACAGACATGCACGCACACCTCAGTTTCACACCCTCTCTCTTATCTGTAAATTACAGATACTAAGTCAGTTTCTTCATATTTATCTGATATTTTAACTACTATTTATCCTGTTGTACGTCAATAAACGTTTTGTAGTGAAAAAAAAAAAAAAAAAAAAAAAAAAGTACTCTGCGTTGATACCACTGCTT
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~A~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this. The error comes from Biopython, the module I use to parse fastq files. It does suggest something is wrong with your input file. Is that a sequence without a phred quality string in your example?

Wouter

**Comment by NiklasDreyer** [comment]
Thanks for the fast reply. The message box cut my fastq file. Looks completely normal (see below)

Have you encountered similar problems with CCS fastq files before? Guess the file is too big to inspect manually but it looks good. 

@m54057_190926_040405/4194389/ccs
GCAATGAAGTCGCAGGGTTGGGATCAGTTGATTCTGACCAACCGTCCAGCACTCGACATGTTCCAGATCGTCCTCGTCGCCGCCCTCGTGGCCTCCGCTGCCGCCGCCAACACTGGCTACAGGGCCCCTTCATACGGCCATGCCGCCGCCCCCGCCTACGGAGGCCACCGTGCCGCCGGATACGGTTACGGCGCCGACTACTATGAGGAGCCCAACTACAACTACGAGTACGCCGTGAAGGACGACTACAGCGGCAACGACTTCGGCCAGACTGAGTACCGTGACGGATACAGCACCAAGGGATCCTACTCCGTCGCCCTCCCCGACGGCCGCACCCAGACCGTCACCTACGCCGATGATGGCTACGGTCTCGTTGCCGACGTCTCCTACTACGGCGAGGCCCGCTACGACAGCTACGGACACGGATATGCTGCCCCATCTTACGGCTACAAGGCCGCTCCCTCTTATGGCCATGCCCGTCCTTCCTACGGATACAAGGCTGCTCCTTCTTATGGATACAAGGCCGCTCCCTCTTACGGATACAGGGCTGCCGCTCCCTCTTACGGGTACAGGGCTGCCGCTCCTTCTTATGGCTACAGAGCCGCCCCCGCTTACGGATATAGCCGTCCCTCTTATGGATACAGCCGTCCCTCCTACGGATACGGATACAGCCGTCCTTCTTACGGATACAGAGCCGCTGCTCCCGCTTACGGCAAGCACTAAGTAGAGACATGAACAAACCCGTCTTCTTTCTTCTCTCATACCATCTGGCTATCGCAATTTGATTGTGCTCTCCTACTTTACCCATCCGCATTCAGCTCATTCCAACTTTCCACAGACATGCACGCACACCTCAGTTTCACACCCTCTCTCTTATCTGTAAATTACAGATACTAAGTCAGTTTCTTCATATTTATCTGATATTTTAACTACTATTTATCCTGTTGTACGTCAATAAACGTTTTGTAGTGAAAAAAAAAAAAAAAAAAAAAAAAAAGTACTCTGCGTTGATACCACTGCTT
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~A~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by NiklasDreyer** [comment]
I just ran NanoPlot with the Isoseq fastq file instead of the CCS fastq file. It runs something and generates a few plots, which does not look like the traditional NanoPlot plots. My command is: NanoPlot -t 2 --raw -o <DIR> -p plot --maxlength 10000 --minlength 50 --color yellow --N50 --title <TITLEa> --fastq <FASTQ> 

Any ideas how to fix this? The fastq files are "raw" and unedited from the sequencing core.

### log exempt ###

2021-11-13 12:22:13,624 NanoPlot 1.32.1 started with arguments Namespace(N50=True, alength=False, bam=None, barcoded=False, color='yellow', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['hq_isoseq_transcripts.fastq'], fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=10000, minlength=50, minqual=None, no_N50=False, no_supplementary=False, outdir='/Users/niklasdreyer/Desktop/nanoplot', path='/Users/niklasdreyer/Desktop/nanoplot/plot', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='plot', raw=True, readtype='1D', runtime_until=None, store=False, summary=None, threads=2, title='CCS_raw_Q20_Facetotecta', tsv_stats=False, ubam=None, verbose=False)
2021-11-13 12:22:13,624 Python version is: 3.7.7 (default, Mar 26 2020, 10:32:53)  [Clang 4.0.1 (tags/RELEASE_401/final)]
2021-11-13 12:22:13,626 NanoPlot:  valid output format png
2021-11-13 12:22:13,655 Nanoget: Starting to collect statistics from plain fastq file.
2021-11-13 12:22:13,656 Nanoget: File provided doesn't exist or the path is incorrect: hq_isoseq_transcripts.fastq
2021-11-13 12:22:44,166 NanoPlot 1.32.1 started with arguments Namespace(N50=True, alength=False, bam=None, barcoded=False, color='yellow', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['/Users/niklasdreyer/Desktop/nanoplot/hq_isoseq_transcripts.fastq'], fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format='png', hide_stats=False, huge=False, listcolormaps=False, listcolors=False, loglength=False, maxlength=10000, minlength=50, minqual=None, no_N50=False, no_supplementary=False, outdir='/Users/niklasdreyer/Desktop/nanoplot', path='/Users/niklasdreyer/Desktop/nanoplot/plot', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='plot', raw=True, readtype='1D', runtime_until=None, store=False, summary=None, threads=2, title='CCS_raw_Q20_Facetotecta', tsv_stats=False, ubam=None, verbose=False)
2021-11-13 12:22:44,217 Python version is: 3.7.7 (default, Mar 26 2020, 10:32:53)  [Clang 4.0.1 (tags/RELEASE_401/final)]
2021-11-13 12:22:44,218 NanoPlot:  valid output format png
2021-11-13 12:22:44,235 Nanoget: Starting to collect statistics from plain fastq file.
2021-11-13 12:22:51,948 Reduced DataFrame memory usage from 0.8154830932617188Mb to 0.47569847106933594Mb
2021-11-13 12:22:51,967 Nanoget: Gathered all metrics of 35629 reads
2021-11-13 12:22:52,168 Calculated statistics
2021-11-13 12:22:52,169 Using sequenced read lengths for plotting.
2021-11-13 12:22:52,174 Hidding 0 reads longer than 10000bp in length plots.
2021-11-13 12:22:52,177 Hidding 0 reads shorter than 50bp in length plots.
2021-11-13 12:22:52,180 NanoPlot:  Valid color yellow.
2021-11-13 12:22:52,182 NanoPlot:  Valid colormap Greens.
2021-11-13 12:22:52,186 NanoPlot:  Creating length plots for Read length.
2021-11-13 12:22:52,187 NanoPlot:  Using 35629 reads with read length N50 of 1771bp and maximum of 7784bp.
2021-11-13 12:22:54,350 Nanoplotter: orca not found, not creating static image of html. See https://github.com/plotly/orca
2021-11-13 12:22:54,350 Image generation requires the psutil package.

Install using pip:
    $ pip install psutil

Install using conda:
    $ conda install psutil
Traceback (most recent call last):
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplotter/plot.py", line 60, in save_static
    pio.write_image(self.fig, self.path.replace('html', 'png'))
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/plotly/io/_kaleido.py", line 252, in write_image
    engine=engine,
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/plotly/io/_kaleido.py", line 109, in to_image
    validate=validate,
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/plotly/io/_orca.py", line 1535, in to_image
    ensure_server()
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/plotly/io/_orca.py", line 1370, in ensure_server
    """
ValueError: Image generation requires the psutil package.

Install using pip:
    $ pip install psutil

Install using conda:
    $ conda install psutil

2021-11-13 12:22:54,613 Created length plots
2021-11-13 12:22:54,617 NanoPlot:  Creating Read lengths vs Average read quality plots using statistics from 35629 reads.
2021-11-13 12:22:54,842 'PathCollection' object has no property 'stat_func'
Traceback (most recent call last):
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 169, in make_plots
    plot_settings=plot_settings)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py", line 169, in scatter
    joint_kws={"s": 1})
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/axisgrid.py", line 2244, in jointplot
    grid.plot_joint(scatterplot, **joint_kws)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/axisgrid.py", line 1806, in plot_joint
    func(x=self.x, y=self.y, **kwargs)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/relational.py", line 827, in scatterplot
    p.plot(ax, kwargs)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/relational.py", line 608, in plot
    scout = ax.scatter(scout_x, scout_y, **kws)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4597, in scatter
    collection.update(kwargs)
  File "/Users/niklasdreyer/miniconda3/envs/nanoplot/lib/python3.7/site-packages/matplotlib/artist.py", line 1062, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'PathCollection' object has no property 'stat_func'
