### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/executable/kaleido'

### ISSUE THREAD

**Issue by AGI-chandler** [wdecoster/NanoPlot#296]
```
2022-04-29 15:36:37,167 NanoPlot 1.40.0 started with arguments Namespace(threads=50, verbose=False, store=False, raw=False, huge=False, outdir='leersia_perrieri_Nplot', no_static=False, prefix='', tsv_stats=False, info_in_report=False, maxlength=None, minlength=None, drop_outliers=False, downsample=None, loglength=False, percentqual=False, alength=False, minqual=None, runtime_until=None, readtype='1D', barcoded=False, no_supplementary=False, color='#4CB391', colormap='Greens', format=['png'], plots=['kde', 'dot'], legacy=None, listcolors=False, listcolormaps=False, no_N50=False, N50=True, title=None, font_scale=1, dpi=100, hide_stats=False, fastq=['/opt/pacbio/smrtlink/userdata/jobs_root/0000/0000001/0000001189/outputs/fastx_files/demultiplex.bc1001_BAK8A_OA--bc1001_BAK8A_OA.hifi_reads.fastq.gz'], fasta=None, fastq_rich=None, fastq_minimal=None, summary=None, bam=None, ubam=None, cram=None, pickle=None, feather=None, path='leersia_perrieri_Nplot/')
2022-04-29 15:36:37,167 Python version is: 3.9.6 (default, Aug 25 2021, 16:22:38)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
2022-04-29 15:36:37,181 Nanoget: Starting to collect statistics from plain fastq file.
2022-04-29 15:36:37,181 Nanoget: Decompressing gzipped fastq /opt/pacbio/smrtlink/userdata/jobs_root/0000/0000001/0000001189/outputs/fastx_files/demultiplex.bc1001_BAK8A_OA--bc1001_BAK8A_OA.hifi_reads.fastq.gz
2022-04-29 15:56:37,636 Reduced DataFrame memory usage from 14.675338745117188Mb to 7.337730407714844Mb
2022-04-29 15:56:37,663 Nanoget: Gathered all metrics of 961755 reads
2022-04-29 15:56:38,093 Calculated statistics
2022-04-29 15:56:38,094 Using sequenced read lengths for plotting.
2022-04-29 15:56:38,125 NanoPlot:  Valid color #4CB391.
2022-04-29 15:56:38,126 NanoPlot:  Valid colormap Greens.
2022-04-29 15:56:38,222 NanoPlot:  Creating length plots for Read length.
2022-04-29 15:56:38,223 NanoPlot: Using 961755 reads with read length N50 of 15886bp and maximum of 54579bp.
2022-04-29 15:56:38,304 [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/executable/kaleido'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nanoplot/NanoPlot.py", line 109, in main
    plots = make_plots(datadf, settings)
  File "/usr/local/lib/python3.9/site-packages/nanoplot/NanoPlot.py", line 169, in make_plots
    nanoplotter.length_plots(
  File "/usr/local/lib/python3.9/site-packages/nanoplotter/nanoplotter_main.py", line 423, in length_plots
    histogram.save(settings)
  File "/usr/local/lib/python3.9/site-packages/nanoplotter/plot.py", line 47, in save
    self.save_static(fmt)
  File "/usr/local/lib/python3.9/site-packages/nanoplotter/plot.py", line 70, in save_static
    f.write(scope.transform(self.fig, format=figformat))
  File "/usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/scopes/plotly.py", line 153, in transform
    response = self._perform_transform(
  File "/usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/scopes/base.py", line 293, in _perform_transform
    self._ensure_kaleido()
  File "/usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/scopes/base.py", line 177, in _ensure_kaleido
    self._proc = subprocess.Popen(
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/executable/kaleido'

```

**Comment by AGI-chandler** [comment]
```
chmod +x /usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/executable/kaleido
chmod +x /usr/local/lib/python3.9/site-packages/kaleido-0.2.1-py3.9-linux-x86_64.egg/kaleido/executable/bin/kaleido
```
fixes it.  Guess it is a problem with kaleido anyways...
