### ISSUE TITLE
NanoPlot crashed - OSError: [Errno 24] 

### ISSUE THREAD

**Issue by AndiBagi** [wdecoster/NanoPlot#315]
Hi,

Thank you for your work invested in NanoPlot!

I have been using it successfully so far - but since I reinstalled it using pip, I am getting the below error message after nanoplot crashes. The input summary file is rather large (~6 GB). I am using a linux operative system - attached you can see the log file. 

Thank you for any comments & hints in advance!
Andrea 

Traceback (most recent call last):
  File "/home/ansatt/andibagi/miniconda3/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 100, in main
    make_plots(dfbarc, settings)
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 218, in make_plots
    settings=settings)
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/nanoplotter/spatial_heatmap.py", line 95, in spatial_heatmap
    activity_map.save(settings)
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/nanoplotter/plot.py", line 47, in save
    self.save_static(fmt)
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/nanoplotter/plot.py", line 70, in save_static
    f.write(scope.transform(self.fig, format=figformat))
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/kaleido/scopes/plotly.py", line 154, in transform
    figure, format=format, width=width, height=height, scale=scale
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/kaleido/scopes/base.py", line 293, in _perform_transform
    self._ensure_kaleido()
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/site-packages/kaleido/scopes/base.py", line 182, in _ensure_kaleido
    shell=sys.platform == "win32"
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/ansatt/andibagi/miniconda3/lib/python3.6/subprocess.py", line 1254, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

 
[NanoPlot_20221028_1149.log](https://github.com/wdecoster/NanoPlot/files/9887344/NanoPlot_20221028_1149.log)

**Comment by wdecoster** [comment]
I haven't see this error before, was it only a temporary thing or could you replicate this on a later day?

**Comment by AndiBagi** [comment]
I got the same error on two consecutive days - haven't tried more afterwards.

**Comment by dgiguer** [comment]
Doing `ulimit -n 2048` was a quick fix for me!

See https://stackoverflow.com/questions/39537731/errno-24-too-many-open-files-but-i-am-not-opening-files
