### ISSUE TITLE
TypeError: can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by Fjhyolanda** [wdecoster/NanoPlot#316]
2022-10-31 08:53:42,134 NanoPlot 1.40.2 started with arguments Namespace(threads=2, verbose=False, store=False, raw=False, huge=False, outdir='.', no_static=False, prefix='', tsv_stats=False, info_in_report=False, maxlength=40000, minlength=None, drop_outliers=False, downsample=None, loglength=False, percentqual=False, alength=False, minqual=None, runtime_until=None, readtype='1D', barcoded=False, no_supplementary=False, color='#4CB391', colormap='Greens', format=['png'], plots=['dot'], legacy=['hex'], listcolors=False, listcolormaps=False, no_N50=False, N50=False, title=None, font_scale=1, dpi=100, hide_stats=False, fastq=['MinION.fastq.gz'], fasta=None, fastq_rich=None, fastq_minimal=None, summary=None, bam=None, ubam=None, cram=None, pickle=None, feather=None, path='./')
2022-10-31 08:53:42,135 Python version is: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]
2022-10-31 08:53:42,194 Nanoget: Starting to collect statistics from plain fastq file.
2022-10-31 08:53:42,197 Nanoget: Decompressing gzipped fastq MinION.fastq.gz
2022-10-31 08:53:48,975 Reduced DataFrame memory usage from 0.7935791015625Mb to 0.29766845703125Mb
2022-10-31 08:53:48,989 Nanoget: Gathered all metrics of 52000 reads
2022-10-31 08:53:49,026 Calculated statistics
2022-10-31 08:53:49,027 Using sequenced read lengths for plotting.
2022-10-31 08:53:49,033 Hidding 0 reads longer than 40000bp in length plots.
2022-10-31 08:53:49,038 NanoPlot:  Valid color #4CB391.
2022-10-31 08:53:49,038 NanoPlot:  Valid colormap Greens.
2022-10-31 08:53:49,041 NanoPlot:  Creating length plots for Read length.
2022-10-31 08:53:49,041 NanoPlot:  Using 52000 reads maximum of 16855bp.
2022-10-31 08:54:11,269 No static plots are saved due to some kaleido problem:
2022-10-31 08:54:11,269 Transform failed with error code 1: Failed to serialize document: Uncaught
2022-10-31 08:54:32,659 No static plots are saved due to some kaleido problem:
2022-10-31 08:54:32,659 Transform failed with error code 1: Failed to serialize document: Uncaught
2022-10-31 08:54:54,314 No static plots are saved due to some kaleido problem:
2022-10-31 08:54:54,315 Transform failed with error code 1: Failed to serialize document: Uncaught
2022-10-31 08:55:15,944 No static plots are saved due to some kaleido problem:
2022-10-31 08:55:15,944 Transform failed with error code 1: Failed to serialize document: Uncaught
2022-10-31 08:55:41,192 No static plots are saved due to some kaleido problem:
2022-10-31 08:55:41,193 Transform failed with error code 1: Failed to serialize document: Uncaught
2022-10-31 08:55:41,196 Created length plots
2022-10-31 08:55:41,300 NanoPlot: Creating Read lengths vs Average read quality plots using 52000 reads.
2022-10-31 08:56:03,774 No static plots are saved due to some kaleido problem:
2022-10-31 08:56:03,774 Transform failed with error code 1: Failed to serialize document: Uncaught
2022-10-31 08:56:06,370 NanoPlot: Creating Read lengths vs Average read quality legacy plots using 10000 reads.
2022-10-31 08:56:06,379 can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/fjh/anaconda3/envs/nanoQC/lib/python3.10/site-packages/nanoplot/NanoPlot.py", line 109, in main
    plots = make_plots(datadf, settings)
  File "/home/fjh/anaconda3/envs/nanoQC/lib/python3.10/site-packages/nanoplot/NanoPlot.py", line 181, in make_plots
    nanoplotter.scatter(
  File "/home/fjh/anaconda3/envs/nanoQC/lib/python3.10/site-packages/nanoplotter/nanoplotter_main.py", line 182, in scatter
    plots_made += scatter_legacy(
  File "/home/fjh/anaconda3/envs/nanoQC/lib/python3.10/site-packages/nanoplotter/nanoplotter_main.py", line 255, in scatter_legacy
    path=path + "_hex." + figformat,
TypeError: can only concatenate str (not "list") to str

**Comment by Fjhyolanda** [comment]
Thanks a lot!
