### ISSUE TITLE
module 'matplotlib.cm' has no attribute 'cmap_d'

### ISSUE THREAD

**Issue by Ghahfarokhi** [wdecoster/NanoPlot#333]
Hi,

Please can you help me with solving the following error? Here is the traceback (I am running NanoPlot from within a conda environment, installed using conda, NanoPlot version: 1.30.1): 

Traceback (most recent call last):
  File "/Users/amir/Assembly_ONT/.snakemake/conda/4662e0a5ca323c0a576ce5c7b9180b4e/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/Users/amir/Assembly_ONT/.snakemake/conda/4662e0a5ca323c0a576ce5c7b9180b4e/lib/python3.10/site-packages/nanoplot/NanoPlot.py", line 97, in main
    plots = make_plots(datadf, settings)
  File "/Users/amir/Assembly_ONT/.snakemake/conda/4662e0a5ca323c0a576ce5c7b9180b4e/lib/python3.10/site-packages/nanoplot/NanoPlot.py", line 134, in make_plots
    colormap = nanoplotter.check_valid_colormap(settings["colormap"])
  File "/Users/amir/Assembly_ONT/.snakemake/conda/4662e0a5ca323c0a576ce5c7b9180b4e/lib/python3.10/site-packages/nanoplotter/nanoplotter_main.py", line 65, in check_valid_colormap
    if colormap in list(cm.cmap_d.keys()):
AttributeError: module 'matplotlib.cm' has no attribute 'cmap_d'

**Comment by wdecoster** [comment]
Hi,

Can you tell me the matplotlib version you have? NanoPlot is currently at v1.41.3, so you could also consider upgrading.

Wouter

**Comment by LHsoerensen** [comment]
Hey,

i am encountering the same issue,
My matplotlib version should be 3.7.1
I just installed Nanoplot using:
>pip install -t /path/i/want NanoPlot
But when running the tool, the version is still displayed as v1.41.0, even when i upgrade an the message shows 1.41.6 was successfully installed.

Any ideas for a work around ?
best,
Lauge

**Comment by wdecoster** [comment]
You probably have multiple installations of NanoPlot. You can try `which NanoPlot` to see where it is.

**Comment by LHsoerensen** [comment]
Hey and thanks for the quick reply,
the issue was solved by adding the nanoplot folder to my python path
>export PYTHONPATH="/my/nanoplot/path"

best
