### ISSUE TITLE
No module named concurrent.futures

### ISSUE THREAD

**Issue by gabyrech** [wdecoster/NanoPlot#34]
Hi! Iam trying to use your tool, but I am getting this error:
What I am missong?
Thanks!

~$ NanoPlot 
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 18, in <module>
    from nanoget import get_input
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 29, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

**Comment by wdecoster** [comment]
As specified in the manual this script is for Python3, and I would strongly suggest you to update. Python2.7 will not be around forever, and except for some legacy systems or old scripts there is no good reason not to change.

I don't plan to support Python2.7.

**Comment by gabyrech** [comment]
Ups, you're rigth! sorry about that. I did'nt see it.
Thanks!
Gabriel

**Comment by wdecoster** [comment]
No worries, I'm glad when problems are easily solved. Please let me know if you encounter issues or have suggestions/feature requests!
