### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by axelphilip** [wdecoster/NanoPlot#362]
Good morning,

I am new to using the MinION sequencing device and am currently exploring various analysis pipelines. Although I am not an experienced coder or bioinformatician, I am eager to learn and expand my skill set.

While attempting to analyze my data using NanoPlot, I encountered an error that I could not resolve through initial searches or checking existing issues on relevant forums. The error message is as follows:
`TypeError: length_plots() got an unexpected keyword argument 'settings'`

Here is the log : 
```
2024-04-12 11:20:40,050 NanoPlot 1.42.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format=['png'], hide_stats=False, huge=False, info_in_report=False, legacy=None, listcolormaps=False, listcolors=False, loglength=True, maxlength=None, minlength=None, minqual=None, no_N50=False, no_static=False, no_supplementary=False, only_report=False, outdir='summary-plots-log-transformed', path='summary-plots-log-transformed/', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=['Bureau/sequencing_summary.txt'], threads=4, title=None, tsv_stats=False, ubam=None, verbose=True)
2024-04-12 11:20:40,050 Python version is: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
2024-04-12 11:20:40,057 Nanoget: Collecting metrics from summary file Bureau/sequencing_summary.txt for 1D sequencing
2024-04-12 11:20:40,258 Nanoget: Finished collecting statistics from summary file Bureau/sequencing_summary.txt
2024-04-12 11:20:40,275 Reduced DataFrame memory usage from 4.122711181640625Mb to 4.122711181640625Mb
2024-04-12 11:20:40,300 Nanoget: Gathered all metrics of 90062 reads
2024-04-12 11:20:40,336 Calculated statistics
2024-04-12 11:20:40,337 Using sequenced read lengths for plotting.
2024-04-12 11:20:40,337 Using log10 scaled read lengths.
2024-04-12 11:20:40,344 Nanoplotter: Valid color #4CB391.
/usr/lib/python3.8/_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
/usr/lib/python3.8/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
2024-04-12 11:20:40,345 Nanoplotter: Valid colormap Greens.
2024-04-12 11:20:40,350 length_plots() got an unexpected keyword argument 'settings'
Traceback (most recent call last):
  File "/home/bforcure/.local/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 110, in main
    plots = make_plots(datadf, settings)
  File "/home/bforcure/.local/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 166, in make_plots
    nanoplotter.length_plots(
TypeError: length_plots() got an unexpected keyword argument 'settings'
```

I would appreciate any guidance or suggestions on how to resolve this error. Thank you in advance for your time and help.

Best,

Axel

**Comment by wdecoster** [comment]
Odd! Is this a recent NanoPlot installation? How did you install this?

**Comment by axelphilip** [comment]
It is indeed a recent NanoPlot installation. I installed using `pip install NanoPlot`.

**Comment by wdecoster** [comment]
Can you try again after pip uninstall nanoplotter

**Comment by wdecoster** [comment]
Hrm but you should just uninstall nanoplotter, not install it again. Not sure if that is the cause though, just my first guess.

**Comment by axelphilip** [comment]
I did uninstall and install it again, my bad. It now reports that it cannot find the 'plotly.graph_objs' module, even though I tried to uninstall and install/upgrade NanoPlot again:

```
NanoPlot --summary Bureau/sequencing_summary.txt --loglength -o summary-plots-log-transformed --verbose
Traceback (most recent call last):
  File "/home/bforcure/.local/bin/NanoPlot", line 5, in <module>
    from nanoplot.NanoPlot import main
  File "/home/bforcure/.local/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 24, in <module>
    from nanoplotter.plot import Plot
  File "/home/bforcure/.local/lib/python3.8/site-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter_main import *
  File "/home/bforcure/.local/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 26, in <module>
    import plotly.graph_objs as go
ModuleNotFoundError: No module named 'plotly.graph_objs'
```

**Comment by wdecoster** [comment]
Hrm. Maybe try uninstalling nanoplot, nanoplotter, nanopack... and install again. I get the idea it is trying to import an old nanoplotter module (which is no longer used by NanoPlot).

**Comment by axelphilip** [comment]
I tried to uninstall and install again everything, rebooted my computer but still stuck on the `ModuleNotFoundError: No module named 'plotly.graph_objs'`

**Comment by wdecoster** [comment]
Does pip install plotly work? If not, maybe try with conda?

**Comment by axelphilip** [comment]
I uninstalled and installed plotly again, and it finally worked. Thanks for the help !

**Comment by wdecoster** [comment]
Not sure what was going on, but glad it is solved :)
