### ISSUE TITLE
I am facing of crashing of Nanoplot

### ISSUE THREAD

**Issue by bhartimittal2976** [wdecoster/NanoPlot#386]
If you read this then NanoPlot 1.42.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 110, in main
    plots = make_plots(datadf, settings)
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 166, in make_plots
    nanoplotter.length_plots(
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 510, in length_plots
    yield_by_minimal_length_plot(
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 564, in yield_by_minimal_length_plot
    fig = px.scatter(df, x=df.reindex(idx)["lengths"], y=df.reindex(idx)["cumyield_gb"])
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 52, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/lib/python3.8/site-packages/plotly/express/_core.py", line 868, in make_figure
    trace_specs, grouped_mappings, sizeref, show_colorbar = infer_config(
  File "/mnt/lustre/RDS-live/mittal/miniconda3/envs/nanopore_qc/lib/python3.8/site-packages/plotly/express/_core.py", line 748, in infer_config
    raise ValueError(
ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['lengths', 'cumyield_gb'] but received: 4      954

**Comment by wdecoster** [comment]
I will need some more information

**Comment by bhartimittal2976** [comment]
let me know what information you would require

**Comment by bhartimittal2976** [comment]
I have resolved the issue, Thanks
