### ISSUE TITLE
plot_error

### ISSUE THREAD

**Issue by lianmengjie-sys** [wdecoster/NanoPlot#389]
NanoPlot --summary summary.tsv --loglength -o summary

If you read this then NanoPlot 1.30.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/home/gt164/miniconda3/envs/nanopore/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/home/gt164/miniconda3/envs/nanopore/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 97, in main
    plots = make_plots(datadf, settings)
  File "/home/gt164/miniconda3/envs/nanopore/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 149, in make_plots
    title=settings["title"])
  File "/home/gt164/miniconda3/envs/nanopore/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 293, in length_plots
    histogram.save(format=figformat)
  File "/home/gt164/miniconda3/envs/nanopore/lib/python3.6/site-packages/nanoplotter/plot.py", line 48, in save
    bbox_inches='tight')
  File "/home/gt164/miniconda3/envs/nanopore/lib/python3.6/site-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
TypeError: print_figure() missing 1 required positional argument: 'filename'

**Comment by wdecoster** [comment]
Hi,

Could you start with upgrading your installation? v1.30.1 is quite old.

Best,
Wouter
