### ISSUE TITLE
Nanoplot installation issue

### ISSUE THREAD

**Issue by ElisaCora** [wdecoster/NanoPlot#395]

**Comment by ElisaCora** [comment]
I have tried then to install the latest version 1.43.0 but got many incompatibilities errors, not copying the full text as it is too long to be accepted. Nevermind, I have tried to install with conda required packages but it was a rabbit hole with no success

nanoplot) gecf@ptegsrv3:Nanoplot_all$ conda install -c bioconda nanoplot=1.43.0
Channels:
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides zlib 1.2.8* needed by samtools-1.7-0

Could not solve for environment specs
The following packages are incompatible
└─ nanoplot 1.43.0**  is not installable because there are no viable options
   ├─ nanoplot 1.43.0 would require
   │  ├─ biopython with the potential options
   │  │  ├─ biopython [1.66|1.67|1.68|1.69] would require
   │  │  │  └─ numpy 1.10* , which does not exist (perhaps a missing channel);
   │  │  ├─ biopython [1.66|1.67|1.69|1.70] would require
   │  │  │  ├─ numpy 1.12* , which can be installed;
   │  │  │  └─ python 2.7*  with the potential options
   │  │  │     ├─ python [2.7.14|2.7.15|...|3.7.7] would require
   │  │  │     │  └─ readline >=7.0,<8.0a0  with the potential options
   │  │  │     │     ├─ readline 7.0, which can be installed;
   │  │  │     │     └─ readline 7.0 would require
   │  │  │     │        └─ ncurses 6.0* , which can be installed;
   │  │  │     ├─ python [2.7.13|2.7.14|3.5.4|3.6.2|3.6.3] would require
   │  │  │     │  └─ ncurses 6.0.* , which can be installed;
   │  │  │     ├─ python [2.7.16|2.7.17] would require
   │  │  │     │  └─ readline >=7.0,<8.0a0  with the potential options
   │  │  │     │     ├─ readline 7.0, which can be installed;
   │  │  │     │     └─ readline 7.0, which can be installed (as previously explained);
   │  │  │     └─ python 2.7.18 conflicts with any installable versions previously reported;
   │  │  ├─ biopython [1.66|1.67|1.69|1.70] would require
   │  │  │  ├─ numpy 1.12* , which can be installed;
   │  │  │  └─ python 3.5*  with the potential options
   │  │  │     ├─ python [2.7.14|2.7.15|...|3.7.7], which can be installed (as previously explained);
   │  │  │     ├─ python [2.7.13|2.7.14|3.5.4|3.6.2|3.6.3], which cannot be installed (as previously explained);
   │  │  │     └─ python 3.5.6 conflicts with any installable versions previously reported;
   │  │  ├─ biopython [1.66|1.67|1.69|1.70] would require
   │  │  │  ├─ numpy 1.12* , which can be installed;
   │  │  │  └─ python 3.6*  with the potential options
   │  │  │     ├─ python [2.7.14|2.7.15|...|3.7.7], which can be installed (as previously explained);
   │  │  │     ├─ python 3.6.10 would require
   │  │  │     │  └─ openssl >=1.1.1g,<1.1.2a , which can be installed;
   │  │  │     ├─ python 3.6.10 would require
   │  │  │     │  └─ openssl >=1.1.1e,<1.1.2a , which can be installed;
   │  │  │     ├─ python [3.6.12|3.6.13] conflicts with any installable versions previously reported;
   │  │  │     ├─ python [2.7.13|2.7.14|3.5.4|3.6.2|3.6.3], which cannot be installed (as previously explained);
   │  │  │     ├─ python 3.6.3 would require
   │  │  │     │  ├─ openssl >=1.0.2m,<1.0.3a , which conflicts with any installable versions previously reported;
   │  │  │     │  └─ readline >=7.0,<8.0a0  with the potential options
   │  │  │     │     ├─ readline 7.0, which can be installed;
   │  │  │     │     └─ readline 7.0, which can be installed (as previously explained);
  
```
And so on

**Comment by ElisaCora** [comment]
Looking into past issues, I found a suggestion to try through pip instead. So I have installed pip and used it to install NanoPlot but I got this error instead

```
(nanoplot) gecf@ptegsrv3:Nanoplot_all$ pip install NanoPlot
Collecting NanoPlot
  Downloading NanoPlot-1.44.0.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
Collecting biopython (from NanoPlot)
  Downloading biopython-1.84.tar.gz (25.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 170.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pysam>0.10.0.0 (from NanoPlot)
  Downloading pysam-0.22.1.tar.gz (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 214.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [190 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: (sysconfig) CC=gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat
      # pysam: (sysconfig) CFLAGS=-fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -Wall    -fPIC   -O2   -isystem /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/include          -fPIC   -O2   -isystem /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/include       -fPIC
      # pysam: (sysconfig) LDFLAGS=-Wl,-rpath,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -Wl,-rpath-link,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -L/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib        -Wl,-rpath,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -Wl,-rpath-link,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -L/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib
      checking for gcc... gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat accepts -g... yes
      checking for gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking how to run the C preprocessor... gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking whether _XOPEN_SOURCE is declared... no
      checking C compiler flags needed for ssse3... -mssse3
      checking C compiler flags needed for popcnt... -mpopcnt
      checking C compiler flags needed for sse4.1... -msse4.1
      checking C compiler flags needed for avx2... -mavx2
      checking C compiler flags needed for avx512f... -mavx512f
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... yes
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      checking for lzma.h... yes
      checking for lzma_easy_buffer_encode in -llzma... yes
      checking whether htscodecs files are present... yes
      checking for libdeflate.h... no
      checking for libdeflate_deflate_compress in -ldeflate... no
      checking for curl/curl.h... no
      checking for curl_easy_pause in -lcurl... no
      checking for curl_easy_init in -lcurl... no
      configure: error: libcurl library not found

      Support for HTTPS and other SSL-based URLs requires routines from the libcurl
      library <http://curl.se/libcurl/>.  Building HTSlib with libcurl enabled
      requires libcurl development files to be installed on the build machine; you
      may need to ensure a package such as libcurl4-{gnutls,nss,openssl}-dev (on
      Debian or Ubuntu Linux) or libcurl-devel (on RPM-based Linux distributions
      or Cygwin) is installed.

      Either configure with --disable-libcurl or resolve this error to build HTSlib.
      checking for gcc... gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat accepts -g... yes
      checking for gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking how to run the C preprocessor... gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/compiler_compat -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking whether _XOPEN_SOURCE is declared... no
      checking C compiler flags needed for ssse3... -mssse3
      checking C compiler flags needed for popcnt... -mpopcnt
      checking C compiler flags needed for sse4.1... -msse4.1
      checking C compiler flags needed for avx2... -mavx2
      checking C compiler flags needed for avx512f... -mavx512f
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... yes
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      checking for lzma.h... yes
      checking for lzma_easy_buffer_encode in -llzma... yes
      checking whether htscodecs files are present... yes
      checking for libdeflate.h... no
      checking for libdeflate_deflate_compress in -ldeflate... no
      configure: WARNING: GCS support not enabled: requires libcurl support
      configure: WARNING: S3 support not enabled: requires libcurl support
      checking for library containing regcomp... none required
      configure: creating ./config.status
      config.status: creating config.mk
      config.status: creating htslib.pc.tmp
      config.status: creating config.h
      config.status: linking htscodecs_bundled.mk to htscodecs.mk
      # pysam: htslib configure options: --disable-libcurl

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Couldn't find previous issues with libcurl, I guess this is something can't just install in my conda environment, right?
Are there alternative solutions?

Thanks
Elisa

**Comment by wdecoster** [comment]
Which operating system are you using to install this on? Is this a personal device?

**Comment by ElisaCora** [comment]
No it is a Linux server, to which people of our lab connect to.

NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.10
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

Thanks!

**Comment by wdecoster** [comment]
Could you try in a new/fresh and empty environment to install with pip? Just want to make sure there are no leftovers from a previous installation causing some trouble.

The main issue in your last installation error is:

```text
Support for HTTPS and other SSL-based URLs requires routines from the libcurl
      library <http://curl.se/libcurl/>.  Building HTSlib with libcurl enabled
      requires libcurl development files to be installed on the build machine; you
      may need to ensure a package such as libcurl4-{gnutls,nss,openssl}-dev (on
      Debian or Ubuntu Linux) or libcurl-devel (on RPM-based Linux distributions
      or Cygwin) is installed
```

So it seems you would need to install libcurl-devel. That is not something specific to NanoPlot - but a dependency for many tools and packages.
Do you have sudo permissions?

**Comment by ElisaCora** [comment]
Ok so I installed libcurl-devel and tried to install again with pip but I still get an error

 pip install NanoPlot
Collecting NanoPlot
  Using cached NanoPlot-1.44.0.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
Collecting biopython (from NanoPlot)
  Using cached biopython-1.84.tar.gz (25.8 MB)
  Preparing metadata (setup.py) ... done
Collecting pysam>0.10.0.0 (from NanoPlot)
  Using cached pysam-0.22.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [120 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: (sysconfig) CC=gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/shared/python_compiler_compat
      # pysam: (sysconfig) CFLAGS=-fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -Wall    -fPIC   -O2   -isystem /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/include          -fPIC   -O2   -isystem /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/include       -fPIC
      # pysam: (sysconfig) LDFLAGS=-Wl,--allow-shlib-undefined -Wl,-rpath,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -Wl,-rpath-link,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -L/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib        -Wl,--allow-shlib-undefined -Wl,-rpath,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -Wl,-rpath-link,/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib -L/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib
      checking for gcc... gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/shared/python_compiler_compat
      checking whether the C compiler works... yes
      checking for C compiler default output file name... a.out
      checking for suffix of executables...
      checking whether we are cross compiling... no
      checking for suffix of object files... o
      checking whether we are using the GNU C compiler... yes
      checking whether gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/shared/python_compiler_compat accepts -g... yes
      checking for gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/shared/python_compiler_compat option to accept ISO C89... none needed
      checking for ranlib... ranlib
      checking for grep that handles long lines and -e... /usr/bin/grep
      checking for C compiler warning flags... unknown
      checking how to run the C preprocessor... gcc -pthread -B /home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/shared/python_compiler_compat -E
      checking for egrep... /usr/bin/grep -E
      checking for ANSI C header files... yes
      checking for sys/types.h... yes
      checking for sys/stat.h... yes
      checking for stdlib.h... yes
      checking for string.h... yes
      checking for memory.h... yes
      checking for strings.h... yes
      checking for inttypes.h... yes
      checking for stdint.h... yes
      checking for unistd.h... yes
      checking whether _XOPEN_SOURCE is declared... no
      checking C compiler flags needed for ssse3... -mssse3
      checking C compiler flags needed for popcnt... -mpopcnt
      checking C compiler flags needed for sse4.1... -msse4.1
      checking C compiler flags needed for avx2... -mavx2
      checking C compiler flags needed for avx512f... -mavx512f
      checking for pkg-config... /usr/bin/pkg-config
      checking pkg-config is at least version 0.9.0... yes
      checking for special C compiler options needed for large files... no
      checking for _FILE_OFFSET_BITS value needed for large files... no
      checking shared library type for unknown-Linux... plain .so
      checking whether the linker supports versioned symbols... no
      checking whether the compiler accepts -fvisibility=hidden... yes
      checking for stdlib.h... (cached) yes
      checking for unistd.h... (cached) yes
      checking for sys/param.h... yes
      checking for getpagesize... yes
      checking for working mmap... yes
      checking for gmtime_r... yes
      checking for fsync... yes
      checking for drand48... yes
      checking for srand48_deterministic... no
      checking whether fdatasync is declared... yes
      checking for fdatasync... yes
      checking for library containing log... -lm
      checking for zlib.h... yes
      checking for inflate in -lz... yes
      checking for library containing recv... none required
      checking for bzlib.h... yes
      checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
      checking for lzma.h... yes
      checking for lzma_easy_buffer_encode in -llzma... yes
      checking whether htscodecs files are present... yes
      checking for libdeflate.h... no
      checking for libdeflate_deflate_compress in -ldeflate... no
      checking for curl/curl.h... yes
      checking for curl_easy_pause in -lcurl... yes
      checking for CCHmac... no
      checking for library containing HMAC... -lcrypto
      checking for library containing regcomp... none required
      configure: creating ./config.status
      config.status: creating config.mk
      config.status: creating htslib.pc.tmp
      config.status: creating config.h
      config.status: linking htscodecs_bundled.mk to htscodecs.mk
      # pysam: htslib configure options: --enable-libcurl
      Traceback (most recent call last):
        File "/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-_s0ez4ov/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_s0ez4ov/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-_s0ez4ov/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_s0ez4ov/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib/python3.13/subprocess.py", line 472, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     **kwargs).stdout
                     ^^^^^^^^^
        File "/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib/python3.13/subprocess.py", line 554, in run
          with Popen(*popenargs, **kwargs) as process:
               ~~~~~^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib/python3.13/subprocess.py", line 1036, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              pass_fds, cwd, env,
                              ^^^^^^^^^^^^^^^^^^^
          ...<5 lines>...
                              gid, gids, uid, umask,
                              ^^^^^^^^^^^^^^^^^^^^^^
                              start_new_session, process_group)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/gecf/softwares/anaconda/[/home/gecf/softwares/anaconda]/envs/nanoplot/lib/python3.13/subprocess.py", line 1966, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'make'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ElisaCora** [comment]
I see the error is still libcurl related, but the installation worked properly 
sudo yum install libcurl-devel
[sudo] password for gecf:
Updating Subscription Management repositories.
Last metadata expiration check: 1:34:22 ago on Thu 19 Dec 2024 08:04:09 AM CET.
Dependencies resolved.
================================================================================================================================================================================
 Package                               Architecture                   Version                                       Repository                                             Size
================================================================================================================================================================================
Installing:
 libcurl-devel                         x86_64                         7.61.1-34.el8_10.2                            rhel-8-for-x86_64-baseos-rpms                         836 k

Transaction Summary
================================================================================================================================================================================
Install  1 Package

Total download size: 836 k
Installed size: 1.3 M
Is this ok [y/N]: y
Downloading Packages:
libcurl-devel-7.61.1-34.el8_10.2.x86_64.rpm                                                                                                     2.8 MB/s | 836 kB     00:00
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                           2.8 MB/s | 836 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                        1/1
  Installing       : libcurl-devel-7.61.1-34.el8_10.2.x86_64                                                                                                                1/1
  Running scriptlet: libcurl-devel-7.61.1-34.el8_10.2.x86_64                                                                                                                1/1
  Verifying        : libcurl-devel-7.61.1-34.el8_10.2.x86_64                                                                                                                1/1
Installed products updated.

Installed:
  libcurl-devel-7.61.1-34.el8_10.2.x86_64

Complete!

**Comment by wdecoster** [comment]
It seems you don't have `make` installed?

**Comment by ElisaCora** [comment]
Thanks! that made it, it finally got installed thorugh pip.
Thank you for your help! 
Happy holidays!

**Comment by wdecoster** [comment]
Good to hear, happy holidays to you too!
