### ISSUE TITLE
LinAlgError("singular matrix")

### ISSUE THREAD

**Issue by euginm** [wdecoster/NanoPlot#47]
Hello,
nanoplot has crashed, raising the LinAlgError("singular matrix") error.

```
2018-02-21 13:26:24,230 NanoPlot 1.10.2 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', cram=None, downsample=None, drop_outliers=False, fasta=None, fastq=['/project/sweet/hiseq/minION/pennelii/SpnLY-PF55-MS01-01-3_S1_L001_R2_001.fastq.gz'], fastq_minimal=None, fastq_rich=None, format='png', listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='/project/sweet/evgeny/minion/QC', percentqual=False, pickle=None, plots=['kde', 'hex', 'dot', 'pauvre'], prefix='', raw=False, readtype='1D', store=False, summary=None, threads=6, title=None, verbose=False)
2018-02-21 13:26:24,231 Python version is: 3.6.4 (default, Feb  5 2018, 14:42:46)  [GCC 5.5.0]
2018-02-21 13:26:24,231 Nanoplotter: valid output format png
2018-02-21 13:26:24,350 Nanoget: Starting to collect statistics from plain fastq file.
2018-02-21 13:26:24,351 Nanoget: Decompressing gzipped fastq /project/sweet/hiseq/minION/pennelii/SpnLY-PF55-MS01-01-3_S1_L001_R2_001.fastq.gz
2018-02-21 13:49:13,974 Nanoget: Gathered all metrics of 16957936 reads
2018-02-21 13:49:21,418 Calculated statistics
2018-02-21 13:49:21,418 Using sequenced read lengths for plotting.
2018-02-21 13:49:21,418 Processed the reads, optionally filtered. 16957936 reads left
2018-02-21 13:49:21,418 Nanoplotter: Valid color #4CB391.
2018-02-21 13:49:21,419 Nanoplotter: Creating length plots for Read length.
2018-02-21 13:49:21,514 Nanoplotter: Using 16957936 reads maximum of 311bp.
2018-02-21 13:49:25,127 Created length plots
2018-02-21 13:49:25,127 Nanoplotter: Creating Read lengths vs Average read quality plots using statistics from 16957936 reads.
2018-02-21 13:50:56,255 singular matrix
Traceback (most recent call last):
  File "/home/muzychen/python/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 86, in main
    plots = make_plots(datadf, settings)
  File "/home/muzychen/python/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 359, in make_plots
    title=settings["title"])
  File "/home/muzychen/python/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 200, in scatter
    size=10)
  File "/home/muzychen/python/lib/python3.6/site-packages/seaborn/axisgrid.py", line 2271, in jointplot
    grid.plot_joint(kdeplot, **joint_kws)
  File "/home/muzychen/python/lib/python3.6/site-packages/seaborn/axisgrid.py", line 1755, in plot_joint
    func(self.x, self.y, **kwargs)
  File "/home/muzychen/python/lib/python3.6/site-packages/seaborn/distributions.py", line 653, in kdeplot
    cbar, cbar_ax, cbar_kws, ax, **kwargs)
  File "/home/muzychen/python/lib/python3.6/site-packages/seaborn/distributions.py", line 385, in _bivariate_kdeplot
    xx, yy, z = _scipy_bivariate_kde(x, y, bw, gridsize, cut, clip)
  File "/home/muzychen/python/lib/python3.6/site-packages/seaborn/distributions.py", line 444, in _scipy_bivariate_kde
    kde = stats.gaussian_kde(data.T)
  File "/home/muzychen/python/lib/python3.6/site-packages/scipy/stats/kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/home/muzychen/python/lib/python3.6/site-packages/scipy/stats/kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "/home/muzychen/python/lib/python3.6/site-packages/scipy/stats/kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/home/muzychen/python/lib/python3.6/site-packages/scipy/linalg/basic.py", line 976, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix
```

Thank you!

**Comment by wdecoster** [comment]
Hi euginm,

Thanks for reporting this. I've never seen this error before, so I'm not really sure where to start. The error is raised when NanoPlot tries to produce the 'kde' plot. Could you try if everything works fine when you limit the plots to dot and hex using `--plot dot hex`? Do you get the same error using the albacore sequencing_summary.txt file as input? 

Could you by chance share your dataset?

I'm not sure if this is related, but it looks like your reads are quite short. How was this dataset generated?

Cheers,
Wouter

**Comment by euginm** [comment]
Wouter,

yes, you are right, I am sorry. The Illumina data was in the same folder with MinIon data! Excluding it from the list gave the desired result.

Thank you again!

**Comment by wdecoster** [comment]
That explains a lot :-)

Please let me know if you encounter further issues or have suggestions/feature requests!
