### ISSUE TITLE
Nanoplot failing with IndexError: list index out of range

### ISSUE THREAD

**Issue by singhindresh** [wdecoster/NanoPlot#54]
My fastq file has only one read and it's failing with following error. Help is appreciated to resolve the issue. Log information is below. If you need fastq file then let me know.

[192> cat runNanpplot.sh.o8811617
Fastq File:fastq_runid_621c072e5213bcc4a880684e33d3c3ac8e9098a5_0.fastq
Dir Name:barcode01

If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!

[193> cat runNanpplot.sh.e8811617
Traceback (most recent call last):
  File "/usr/local/packages/python-3.6.4/bin/NanoPlot", line 11, in <module>
    load_entry_point('NanoPlot==1.8.1', 'console_scripts', 'NanoPlot')()
  File "/usr/local/packages/python-3.6.4/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 64, in main
    outputfile=statsfile)
  File "/usr/local/packages/python-3.6.4/lib/python3.6/site-packages/nanomath/nanomath.py", line 151, in write_stats
    i + 1, feature_list(stats, long_features[lf], index=i)))
  File "/usr/local/packages/python-3.6.4/lib/python3.6/site-packages/nanomath/nanomath.py", line 107, in feature_list
    return '\t'.join([str(s.__dict__[feature][index]) for s in stats])
  File "/usr/local/packages/python-3.6.4/lib/python3.6/site-packages/nanomath/nanomath.py", line 107, in <listcomp>
    return '\t'.join([str(s.__dict__[feature][index]) for s in stats])
IndexError: list index out of range

**Comment by wdecoster** [comment]
This looks like the same issue as https://github.com/wdecoster/NanoPlot/issues/51, and should be solved by updating NanoPlot. The most recent version on PyPI is 1.10.5.

Can you confirm?
