### ISSUE TITLE
concurrent.futures.process._RemoteTraceback: 

### ISSUE THREAD

**Issue by AndrewLeeGla** [wdecoster/NanoPlot#59]
If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!

root@IEMB:/# cat NanoPlot_20180420_2245.log 
2018-04-20 22:45:08,271 NanoPlot 1.13.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', cram=None, downsample=None, drop_outliers=False, fasta=None, fastq=['/Glauconema_0423_nanopore.fastq'], fastq_minimal=None, fastq_rich=None, format='png', listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='.', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', store=False, summary=None, threads=4, title=None, verbose=False)
2018-04-20 22:45:08,272 Python version is: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
2018-04-20 22:45:08,272 Nanoplotter: valid output format png
2018-04-20 22:45:08,277 Nanoget: Starting to collect statistics from plain fastq file.
2018-04-20 22:48:43,311 End of file without quality information.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.5/dist-packages/nanoget/nanoget.py", line 398, in process_fastq_plain
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/usr/local/lib/python3.5/dist-packages/nanoget/nanoget.py", line 398, in <listcomp>
    data=[res for res in extract_from_fastq(inputfastq) if res],
  File "/usr/local/lib/python3.5/dist-packages/nanoget/nanoget.py", line 408, in extract_from_fastq
    for rec in SeqIO.parse(fq, "fastq"):
  File "/usr/local/lib/python3.5/dist-packages/Bio/SeqIO/__init__.py", line 617, in parse
    for r in i:
  File "/usr/local/lib/python3.5/dist-packages/Bio/SeqIO/QualityIO.py", line 1029, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/usr/local/lib/python3.5/dist-packages/Bio/SeqIO/QualityIO.py", line 914, in FastqGeneralIterator
    raise ValueError("End of file without quality information.")
ValueError: End of file without quality information.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nanoplot/NanoPlot.py", line 62, in main
    barcoded=args.barcoded)
  File "/usr/local/lib/python3.5/dist-packages/nanoget/nanoget.py", line 74, in get_input
    dfs=[out for out in executor.map(extration_function, files)],
  File "/usr/local/lib/python3.5/dist-packages/nanoget/nanoget.py", line 74, in <listcomp>
    dfs=[out for out in executor.map(extration_function, files)],
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
ValueError: End of file without quality information.

Thank you!

**Comment by AndrewLeeGla** [comment]
Hi
I desire some help, my computer runs Ubuntu 16.04 system with Core i5 and 16G memory.
Does it enough to run NanoPack with a 5G size fastq file? 
Hope your reply.
Thanks!

**Comment by wdecoster** [comment]
Hi,

The error "End of file without quality information" suggest that something is wrong with your fastq file. 
Could you take a look at the end if it, using tail -n 8 for example to see if it looks okay?

Cheers, 
Wouter

**Comment by wdecoster** [comment]
I don't expect that your computer is the problem.

**Comment by wdecoster** [comment]
That would help, but it would be better to figure out why your file got corrupted. How did you obtain this fastq?

**Comment by wdecoster** [comment]
I will occasionally check this thread but it's Friday evening in my time zone :)

**Comment by AndrewLeeGla** [comment]
OK, Thank you!
I will check it out later. 
Thank you again.
