### ISSUE TITLE
Upgrading NanoPlot

### ISSUE THREAD

**Issue by lfaller** [wdecoster/NanoPlot#64]
Dear @wdecoster,

I also ran into the error reported in #41 today, and I upgraded NanoPlot as follows:

```
$> pip install NanoPlot --upgrade
...
      Successfully uninstalled NanoPlot-0.16.2
Successfully installed NanoPlot-1.8.1 backports.functools-lru-cache-1.5 biopython-1.71 kiwisolver-1.0.1 matplotlib-2.2.2 nanoplotter-0.28.0 numpy-1.14.3 pandas-0.23.0 pauvre-0.1.86 pysam-0.14.1 python-dateutil-2.7.3 pytz-2018.4 scipy-1.1.0 setuptools-39.2.0 subprocess32-3.5.1
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Then I wanted to check the version, but now I get:

```
$> NanoPlot -v
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 24, in <module>
    import nanoplotter
  File "/usr/local/lib/python2.7/dist-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter import *
  File "/usr/local/lib/python2.7/dist-packages/nanoplotter/nanoplotter.py", line 41, in <module>
    from pauvre.marginplot import margin_plot
  File "/usr/local/lib/python2.7/dist-packages/pauvre/marginplot.py", line 360
    file=stderr)
        ^
SyntaxError: invalid syntax
```

For `nanomath` I still get:

```
$> python -c "import nanomath ; print(nanomath.__version__)"
0.15.1
```

Note that I hadn't installed NanoPlot originially with conda.

Do you have any suggestions for how to fix this? At this point, NanoPlot doesn't seem to work anymore.

Thanks for any advice!

**Comment by lfaller** [comment]
By the way, I get the same result if I first uninstall NanoPlot with pip and then reinstall.

**Comment by wdecoster** [comment]
Hi lfaller,

Based on the errror you are trying to install NanoPlot using python 2.7, which is not compatible. Do you have a python 3 installation on your system? You could try:

`python3 -m pip install NanoPlot`

This will make sure the right python interpreter is chosen.

Cheers,
Wouter

**Comment by Garryf** [comment]
haveing trouble installing. I get 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-emasf3xz/nanoplotter/
any ideas.

thanks
Garry

**Comment by wdecoster** [comment]
Please open a separate issue for this and add more information (python version, operating system, all output from pip...).

**Comment by lfaller** [comment]
Thanks for the help, Wouter!

**Comment by wdecoster** [comment]
Did that solve your problem?

**Comment by wdecoster** [comment]
Could start with trying to upgrade pip, as suggested at the bottom of what you just pasted?

`python3 -m  pip install --upgrade pip`

**Comment by lfaller** [comment]
Good point, I did that and got the following message:

```
$> pip3 --version
pip 10.0.1 from /home/lina/.local/lib/python3.5/site-packages/pip (python 3.5)
```

```
Looking in indexes: https://pypi.org/simple, https://pypi.ginkgobioworks.com/simple/
Collecting NanoPlot
  Using cached https://files.pythonhosted.org/packages/0e/a4/d0c8d1a0997be9a6fb3d84ac8479f09985f816c4df6a1e0f65881a1c38f6/NanoPlot-1.13.0.tar.gz
DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Collecting biopython (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/63/26/198e369dd95c50554ccc9ec76719be8e338d171fb30c7f14439653cd9153/biopython-1.71-cp35-cp35m-manylinux1_x86_64.whl
Collecting pysam>0.10.0.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/09/a9/d74aa164efb28ce328cd4890b0182ccdf2e781c192910072717c965765c6/pysam-0.14.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting pandas>=0.22.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/a5/c1/43966a4ce89d0c64111f46c6364ed57d6d87e6fab7d685dca06197a19cf7/pandas-0.23.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from NanoPlot) (1.11.0)
Collecting scipy (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/cd/32/5196b64476bd41d596a8aba43506e2403e019c90e1a3dfc21d51b83db5a6/scipy-1.1.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from NanoPlot) (2.4.2)
Collecting seaborn (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/10/01/dd1c7838cde3b69b247aaeb61016e238cafd8188a276e366d36aa6bcdab4/seaborn-0.8.1.tar.gz
Collecting nanoplotter>=0.36.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/13/48/111eccfee3c8d5d655ff92afb1307d4f1b6cc5d47d865e815d6c8a21e97a/nanoplotter-0.38.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-install-ivir448p/nanoplotter/.eggs/setuptools-39.2.0-py3.5.egg
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ivir448p/nanoplotter/setup.py", line 43, in <module>
        package_dir={'nanoplotter': 'nanoplotter'})
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ivir448p/nanoplotter/
```

**Comment by wdecoster** [comment]
Looks like you may have to upgrade setuptools as well:

`python3 -m pip install --upgrade setuptools`

We'll get there eventually :)

**Comment by lfaller** [comment]
Ok! I had to upgrade setuptools, numpy, and python-dateutil but it looks like I'm all set now -- thanks a bunch!

**Comment by wdecoster** [comment]
Good to hear!
