### ISSUE TITLE
Can I change the font size on the x and y axis in nanoplot

### ISSUE THREAD

**Issue by herrroaa** [wdecoster/NanoPlot#82]

**Comment by wdecoster** [comment]
Currently not, but it would not be impossible to add that. Do you need bigger or smaller text? Do you mean the axis labels or axis title, or all text in the image?

**Comment by herrroaa** [comment]
I want to increase the title and label font size on x and y axes

**Comment by wdecoster** [comment]
I'll take a look at that later since I'm on holiday.

**Comment by wdecoster** [comment]
NanoPlot v1.17.0 (now available on PyPI) has a --font_scale argument (default=1) which you can use to scale the fonts. That is the easiest solution.

**Comment by herrroaa** [comment]
I upgraded to V1.17.0 , but I got an error I did not get before.

$NanoPlot -o Plotsnotitlebiggerfont -f png -p test  --title ' ' --bam BC01_sorted.bam

```
If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!



Traceback (most recent call last):
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 92, in main
    plots = make_plots(datadf, settings)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 324, in make_plots
    plot_settings=plot_settings)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 180, in scatter
    joint_kws={"s": 1})
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/seaborn/axisgrid.py", line 2247, in jointplot
    grid.plot_joint(plt.scatter, **joint_kws)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/seaborn/axisgrid.py", line 1755, in plot_joint
    func(self.x, self.y, **kwargs)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3378, in scatter
    edgecolors=edgecolors, data=data, **kwargs)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4032, in scatter
    collection.update(kwargs)
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/matplotlib/artist.py", line 902, in update
    for k, v in props.items()]
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/matplotlib/artist.py", line 902, in <listcomp>
    for k, v in props.items()]
  File "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/lib/python3.6/site-packages/matplotlib/artist.py", line 895, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property height
(bioinfo) 
```

**Comment by wdecoster** [comment]
Could you add the full log file please?

**Comment by herrroaa** [comment]
[
[font01NanoPlot_20180809_1824.log](https://github.com/wdecoster/NanoPlot/files/2278552/font01NanoPlot_20180809_1824.log)
](url)

**Comment by wdecoster** [comment]
> I upgraded to V1.17.0

How did you upgrade? Just using `pip install NanoPlot -U`?
It seems to me you do not have the latest version of seaborn, which is specified as a dependency by nanoplotter. Can you show me the output of:

```
python -c "import seaborn ; print(seaborn.__version__)"
python -c "import nanoplotter ; print(nanoplotter.__version__)"
```

**Comment by wdecoster** [comment]
Did that solve anything?

**Comment by herrroaa** [comment]
`$ python -c "import seaborn ; print(seaborn.__version__)"
0.8.1

$ python -c "import nanoplotter ; print(nanoplotter.__version__)"
0.41.0
(bioinfo) 
`

**Comment by wdecoster** [comment]
I asked you before: How did you upgrade? Just using `pip install NanoPlot -U`?

Anyway, your seaborn module should be updated to >=0.9.0L
`pip install seaborn -U`
