### ISSUE TITLE
pauvre plot crashes with ZeroDivisionError

### ISSUE THREAD

**Issue by tolot27** [wdecoster/NanoPlot#90]
I've applied NanoPlot v1.17.2 to several `sequencing_summary.txt` with parameter `--plots pauvre` but always got:

```
/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning:

Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.




If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!



Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/nanoplot/NanoPlot.py", line 92, in main
    plots = make_plots(datadf, settings)
  File "/usr/local/lib/python3.6/dist-packages/nanoplot/NanoPlot.py", line 324, in make_plots
    plot_settings=plot_settings)
  File "/usr/local/lib/python3.6/dist-packages/nanoplotter/nanoplotter.py", line 243, in scatter
    QUIET=True)
  File "/usr/local/lib/python3.6/dist-packages/pauvre/marginplot.py", line 340, in margin_plot
    y_label='Read Length', bottom_spine=length_bottom_spine)
  File "/usr/local/lib/python3.6/dist-packages/pauvre/marginplot.py", line 117, in generate_histogram
    bins = np.arange(0, max_plot_length, bin_interval)
ZeroDivisionError: division by zero
```

**Comment by tolot27** [comment]
The log file does not contain more information:

```
2018-09-14 16:41:50,635 NanoPlot 1.17.2 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', cram=None, downsample=None, drop_outliers=False, fasta=None, fastq=None, fastq_minimal=None, fastq_rich=None, font_scale=1, format='pdf', listcolors=False, loglength=True, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='.', percentqual=False, pickle=None, plots=['pauvre'], prefix='MI000-B3266_', raw=False, readtype='1D', runtime_until=None, store=False, summary=['sequencing_summary.txt'], threads=20, title=None, verbose=False)
2018-09-14 16:41:50,635 Python version is: 3.6.5 (default, Apr  1 2018, 05:46:30)  [GCC 7.3.0]
2018-09-14 16:41:50,636 Nanoplotter: valid output format pdf
2018-09-14 16:41:50,644 Nanoget: Collecting metrics from summary file sequencing_summary.txt for 1D sequencing
2018-09-14 16:42:07,779 Nanoget: Finished collecting statistics from summary file sequencing_summary.txt
2018-09-14 16:42:08,112 Reduced DataFrame memory usage from 67671016b to 34120114b
2018-09-14 16:42:08,585 Nanoget: Gathered all metrics of 284332 reads
2018-09-14 16:42:09,039 Calculated statistics
2018-09-14 16:42:09,039 Using sequenced read lengths for plotting.
2018-09-14 16:42:09,060 Using Log10 scaled read lengths.
2018-09-14 16:42:09,060 Processed the reads, optionally filtered. 284332 reads left
2018-09-14 16:42:09,062 Nanoplotter: Valid color #4CB391.
2018-09-14 16:42:09,063 Nanoplotter: Creating length plots for Read length.
2018-09-14 16:42:09,065 Nanoplotter: Using 284332 reads maximum of 104783bp.
2018-09-14 16:42:16,201 Created length plots
2018-09-14 16:42:16,203 Nanoplotter: Creating Read lengths vs Average read quality plots using statistics from 284332 reads.
2018-09-14 16:42:16,361 division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nanoplot/NanoPlot.py", line 92, in main
    plots = make_plots(datadf, settings)
  File "/usr/local/lib/python3.6/dist-packages/nanoplot/NanoPlot.py", line 324, in make_plots
    plot_settings=plot_settings)
  File "/usr/local/lib/python3.6/dist-packages/nanoplotter/nanoplotter.py", line 243, in scatter
    QUIET=True)
  File "/usr/local/lib/python3.6/dist-packages/pauvre/marginplot.py", line 340, in margin_plot
    y_label='Read Length', bottom_spine=length_bottom_spine)
  File "/usr/local/lib/python3.6/dist-packages/pauvre/marginplot.py", line 117, in generate_histogram
    bins = np.arange(0, max_plot_length, bin_interval)
ZeroDivisionError: division by zero
```

**Comment by wdecoster** [comment]
I'll have a look. Tagging @conchoecia

**Comment by wdecoster** [comment]
I have tried, and I cannot replicate this. Could you perhaps share one of those summary files?  
I do get the MatplotlibDeprecationWarning, but no ZeroDivisionError.

And could you also check the version of pauvre? 
python -c "import pauvre; print(pauvre.__version__)

That should be v0.1.86.

Thanks again,
Wouter

**Comment by tolot27** [comment]
`python -c "import pauvre; print(pauvre.__version__)"` returns `0.1.86`.

**Comment by wdecoster** [comment]
Based on your log file you were using `--loglength` here too, which seems to have caused the error. Using `--plot pauvre` with your summary, without `--loglength`, works fine.

I'll dive into the pauvre code, but I'm not the maintainer there.
